//	Header generated by Constructor for Palm OS¨ 1.6
//
//	Generated at 2:59:23 PM on Thursday, March 06, 2003
//
//	Generated for file: C:\Documents and Settings\clemens\My Documents\My Projects\AlphaHacker\Rsc\AlphaHacker.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"AlphaHacker"
//
//	Palm App Version:		"1.12"


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainCreditsField                          1002	//(Left Origin = 104, Top Origin = 0, Width = 50, Height = 12, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 0, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainCrackerGadget                         1004	//(Left Origin = 35, Top Origin = 150, Width = 12, Height = 10, Usable = 1)
#define MainNSLookupGadget                        1008	//(Left Origin = 20, Top Origin = 150, Width = 12, Height = 10, Usable = 1)
#define MainScanGadget                            1009	//(Left Origin = 50, Top Origin = 150, Width = 12, Height = 10, Usable = 1)
#define MainICEBreakerGadget                      1010	//(Left Origin = 65, Top Origin = 150, Width = 12, Height = 10, Usable = 1)
#define MainCompStoreGadget                       1011	//(Left Origin = 80, Top Origin = 150, Width = 12, Height = 10, Usable = 1)
#define MainBlackHatGadget                        1012	//(Left Origin = 95, Top Origin = 150, Width = 12, Height = 10, Usable = 1)
#define MainConnectGadget                         1018	//(Left Origin = 5, Top Origin = 150, Width = 12, Height = 10, Usable = 1)
#define MainDollarLabel                           1001	//(Left Origin = 96, Top Origin = 0, Usable = 1, Font = Bold)
#define MainHostsLabel                            1006	//(Left Origin = 0, Top Origin = 88, Usable = 1, Font = Standard)
#define MainLogLabel                              1007	//(Left Origin = 0, Top Origin = 16, Usable = 1, Font = Standard)
#define MainScrollUpRepeating                     1014	//(Left Origin = 136, Top Origin = 150, Width = 12, Height = 10, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Symbol 7)
#define MainScrollDownRepeating                   1015	//(Left Origin = 148, Top Origin = 150, Width = 12, Height = 10, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Symbol 7)
#define MainEmailScrollUpRepeating                1016	//(Left Origin = 136, Top Origin = 88, Width = 12, Height = 10, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Symbol 7)
#define MainEmailScrollDownRepeating              1017	//(Left Origin = 148, Top Origin = 88, Width = 12, Height = 10, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Symbol 7)
#define MainNSLookupTable                         1003	//(Left Origin = 0, Top Origin = 100, Width = 160, Height = 50, Editable = 1, Rows = 4)
#define MainEmailTable                            1005	//(Left Origin = 0, Top Origin = 28, Width = 160, Height = 60, Editable = 1, Rows = 5)

//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOKButton                             1105	//(Left Origin = 58, Top Origin = 133, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutTitleBitMap                          1700	//(Left Origin = 2, Top Origin = 14, Bitmap Resource ID = 1700, Usable = 1)
#define AboutCopyrightLabel                       1101	//(Left Origin = 3, Top Origin = 60, Usable = 1, Font = Bold)
#define AboutURLLabel                             1103	//(Left Origin = 6, Top Origin = 110, Usable = 1, Font = Bold)
#define AboutText2Label                           1104	//(Left Origin = 3, Top Origin = 50, Usable = 1, Font = Bold)
#define AboutSupportLabel                         1106	//(Left Origin = 6, Top Origin = 86, Usable = 1, Font = Standard)

//	Resource: tFRM 1200
#define UserForm                                  1200	//(Left Origin = 1, Top Origin = 1, Width = 158, Height = 158, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define UserOkButton                              1207	//(Left Origin = 72, Top Origin = 140, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define UserHandleField                           1202	//(Left Origin = 39, Top Origin = 15, Width = 85, Height = 16, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Bold 12, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define UserCPUField                              1204	//(Left Origin = 39, Top Origin = 31, Width = 45, Height = 16, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Bold 12, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define UserRAMField                              1206	//(Left Origin = 111, Top Origin = 31, Width = 45, Height = 16, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Bold 12, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define UserOSField                               1209	//(Left Origin = 39, Top Origin = 63, Width = 85, Height = 16, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Bold 12, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define UserCrackedField                          1211	//(Left Origin = 47, Top Origin = 47, Width = 40, Height = 16, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Bold 12, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define UserRankField                             1213	//(Left Origin = 39, Top Origin = 79, Width = 85, Height = 16, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Bold 12, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define UserScoreField                            1215	//(Left Origin = 118, Top Origin = 47, Width = 40, Height = 16, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Bold 12, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define UserSourceField                           1218	//(Left Origin = 47, Top Origin = 95, Width = 40, Height = 16, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Bold 12, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define UserPayrollField                          1219	//(Left Origin = 47, Top Origin = 119, Width = 40, Height = 16, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Bold 12, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define UserUFOField                              1221	//(Left Origin = 118, Top Origin = 103, Width = 40, Height = 16, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Bold 12, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define UserHandleLabel                           1201	//(Left Origin = 5, Top Origin = 15, Usable = 1, Font = Standard)
#define UserCPULabel                              1203	//(Left Origin = 5, Top Origin = 31, Usable = 1, Font = Standard)
#define UserRAMLabel                              1205	//(Left Origin = 87, Top Origin = 31, Usable = 1, Font = Standard)
#define UserOSLabel                               1208	//(Left Origin = 5, Top Origin = 63, Usable = 1, Font = Standard)
#define UserCrackedLabel                          1210	//(Left Origin = 5, Top Origin = 47, Usable = 1, Font = Standard)
#define UserRankLabel                             1212	//(Left Origin = 5, Top Origin = 79, Usable = 1, Font = Standard)
#define UserScoreLabel                            1214	//(Left Origin = 87, Top Origin = 47, Usable = 1, Font = Standard)
#define UserSourceLabel                           1216	//(Left Origin = 7, Top Origin = 95, Usable = 1, Font = Standard)
#define UserPayrollLabel                          1217	//(Left Origin = 5, Top Origin = 119, Usable = 1, Font = Standard)
#define UserUFOLabel                              1220	//(Left Origin = 87, Top Origin = 103, Usable = 1, Font = Standard)

//	Resource: tFRM 1300
#define WelcomeForm                               1300	//(Left Origin = 1, Top Origin = 1, Width = 158, Height = 120, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define WelcomeLogonButton                        1306	//(Left Origin = 64, Top Origin = 88, Width = 40, Height = 18, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold 12)
#define WelcomeUsernameField                      1303	//(Left Origin = 71, Top Origin = 63, Width = 65, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 12, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define WelcomeUnnamed1304GraffitiShift           1304	//(Left Origin = 143, Top Origin = 103)
#define WelcomeWelcomeLabel                       1301	//(Left Origin = 23, Top Origin = 31, Usable = 1, Font = Bold 12)
#define WelcomeUsernameLabel                      1302	//(Left Origin = 15, Top Origin = 63, Usable = 1, Font = Bold 12)

//	Resource: tFRM 1400
#define SWInventoryForm                           1400	//(Left Origin = 1, Top Origin = 1, Width = 158, Height = 90, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define SWInventoryOkButton                       1401	//(Left Origin = 34, Top Origin = 69, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define SWInventoryScannerField                   1405	//(Left Origin = 70, Top Origin = 15, Width = 80, Height = 12, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define SWInventoryCrackerField                   1406	//(Left Origin = 70, Top Origin = 30, Width = 80, Height = 12, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define SWInventoryICEBreakerField                1407	//(Left Origin = 70, Top Origin = 45, Width = 80, Height = 12, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define SWInventoryScannerLabel                   1402	//(Left Origin = 4, Top Origin = 15, Usable = 1, Font = Bold 12)
#define SWInventoryCrackerLabel                   1403	//(Left Origin = 4, Top Origin = 30, Usable = 1, Font = Bold 12)
#define SWInventoryICELabel                       1404	//(Left Origin = 4, Top Origin = 45, Usable = 1, Font = Bold 12)

//	Resource: tFRM 1500
#define CompStoreForm                             1500	//(Left Origin = 1, Top Origin = 39, Width = 158, Height = 120, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define CompStoreOkButton                         1509	//(Left Origin = 24, Top Origin = 96, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define CompStoreBuyCPUButton                     1510	//(Left Origin = 112, Top Origin = 32, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define CompStoreBuyRAMButton                     1511	//(Left Origin = 112, Top Origin = 72, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define CompStoreCurCPUField                      1502	//(Left Origin = 71, Top Origin = 15, Width = 70, Height = 12, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define CompStoreCurRamField                      1507	//(Left Origin = 71, Top Origin = 55, Width = 70, Height = 12, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define CompStoreCurCPULabel                      1501	//(Left Origin = 7, Top Origin = 15, Usable = 1, Font = Standard)
#define CompStoreCurRAMLabel                      1508	//(Left Origin = 7, Top Origin = 55, Usable = 1, Font = Standard)
#define CompStoreCPUList                          1504	//(Left Origin = 23, Top Origin = 31, Width = 80, Usable = 0, Font = Standard, Visible Items = 4)
#define CompStoreRAMList                          1505	//(Left Origin = 23, Top Origin = 71, Width = 80, Usable = 0, Font = Standard, Visible Items = 4)
#define CompStoreCPUPopTrigger                    1503	//(Left Origin = 23, Top Origin = 31, Width = 80, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1504)
#define CompStoreRAMPopTrigger                    1506	//(Left Origin = 23, Top Origin = 71, Width = 80, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1505)

//	Resource: tFRM 1600
#define BlackHatForm                              1600	//(Left Origin = 1, Top Origin = 1, Width = 158, Height = 158, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define BlackHatOKButton                          1607	//(Left Origin = 64, Top Origin = 144, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define BlackHatBuyOSButton                       1610	//(Left Origin = 112, Top Origin = 32, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define BlackHatBuyScannerButton                  1614	//(Left Origin = 113, Top Origin = 65, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define BlackHatBuyCrackerButton                  1618	//(Left Origin = 113, Top Origin = 97, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define BlackHatBuyICEButton                      1621	//(Left Origin = 113, Top Origin = 129, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define BlackHatICEBreakerField                   1605	//(Left Origin = 87, Top Origin = 111, Width = 70, Height = 12, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define BlackHatOSField                           1606	//(Left Origin = 86, Top Origin = 15, Width = 70, Height = 12, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define BlackHatScannerField                      1611	//(Left Origin = 87, Top Origin = 47, Width = 70, Height = 12, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define BlackHatCrackerField                      1615	//(Left Origin = 87, Top Origin = 79, Width = 70, Height = 12, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define BlackHatOSLabel                           1601	//(Left Origin = 2, Top Origin = 15, Usable = 1, Font = Standard)
#define BlackHatCurScannerLabel                   1602	//(Left Origin = 0, Top Origin = 47, Usable = 1, Font = Standard)
#define BlackHatCurCrackerLabel                   1603	//(Left Origin = 0, Top Origin = 79, Usable = 1, Font = Standard)
#define BlackHatCurBreakerLabel                   1604	//(Left Origin = 2, Top Origin = 111, Usable = 1, Font = Standard)
#define BlackHatOSList                            1609	//(Left Origin = 7, Top Origin = 31, Width = 90, Usable = 0, Font = Standard, Visible Items = 3)
#define BlackHatScannerList                       1613	//(Left Origin = 8, Top Origin = 64, Width = 90, Usable = 0, Font = Standard, Visible Items = 3)
#define BlackHatCrackerList                       1617	//(Left Origin = 8, Top Origin = 96, Width = 90, Usable = 0, Font = Standard, Visible Items = 3)
#define BlackHatICEBreakerList                    1620	//(Left Origin = 8, Top Origin = 128, Width = 90, Usable = 0, Font = Standard, Visible Items = 2)
#define BlackHatOSPopTrigger                      1608	//(Left Origin = 7, Top Origin = 31, Width = 80, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1609)
#define BlackHatScannerPopTrigger                 1612	//(Left Origin = 8, Top Origin = 64, Width = 80, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1613)
#define BlackHatCrackerPopTrigger                 1616	//(Left Origin = 8, Top Origin = 96, Width = 80, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1617)
#define BlackHatICEBreakerPopTrigger              1619	//(Left Origin = 8, Top Origin = 128, Width = 80, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1620)

//	Resource: tFRM 1800
#define EmailViewForm                             1800	//(Left Origin = 1, Top Origin = 1, Width = 158, Height = 158, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define EmailViewOkButton                         1807	//(Left Origin = 32, Top Origin = 144, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define EmailViewDeleteButton                     1808	//(Left Origin = 88, Top Origin = 144, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define EmailViewFromField                        1804	//(Left Origin = 47, Top Origin = 15, Width = 100, Height = 12, Usable = 1, Editable = 0, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define EmailViewSubjectField                     1805	//(Left Origin = 47, Top Origin = 31, Width = 100, Height = 12, Usable = 1, Editable = 0, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define EmailViewMessageField                     1806	//(Left Origin = 7, Top Origin = 63, Width = 140, Height = 80, Usable = 1, Editable = 0, Underline = 1, Single Line = 0, Dynamic Size = 1, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 1, Numeric = 0)
#define EmailViewFromLabel                        1801	//(Left Origin = 7, Top Origin = 15, Usable = 1, Font = Standard)
#define EmailViewSubjectLabel                     1802	//(Left Origin = 7, Top Origin = 31, Usable = 1, Font = Standard)
#define EmailViewMessageLabel                     1803	//(Left Origin = 7, Top Origin = 47, Usable = 1, Font = Standard)

//	Resource: tFRM 1700
#define CrackForm                                 1700	//(Left Origin = 15, Top Origin = 20, Width = 120, Height = 90, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define CrackCrackButton                          1703	//(Left Origin = 7, Top Origin = 69, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define CrackDisconnectButton                     1704	//(Left Origin = 50, Top Origin = 69, Width = 50, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define CrackAddressField                         1702	//(Left Origin = 49, Top Origin = 20, Width = 60, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define CrackTimerField                           1707	//(Left Origin = 49, Top Origin = 52, Width = 60, Height = 12, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define CrackOutput1Field                         1708	//(Left Origin = 30, Top Origin = 36, Width = 8, Height = 16, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Bold 12, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define CrackOutput2Field                         1709	//(Left Origin = 40, Top Origin = 36, Width = 8, Height = 16, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Bold 12, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define CrackOutput3Field                         1710	//(Left Origin = 50, Top Origin = 36, Width = 8, Height = 16, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Bold 12, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define CrackOutput4Field                         1711	//(Left Origin = 60, Top Origin = 36, Width = 8, Height = 16, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Bold 12, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define CrackOutput5Field                         1712	//(Left Origin = 70, Top Origin = 36, Width = 8, Height = 16, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Bold 12, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define CrackOutput6Field                         1713	//(Left Origin = 80, Top Origin = 36, Width = 8, Height = 16, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Bold 12, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define CrackOutput7Field                         1714	//(Left Origin = 90, Top Origin = 36, Width = 8, Height = 16, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Bold 12, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define CrackOutput8Field                         1715	//(Left Origin = 100, Top Origin = 36, Width = 8, Height = 16, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Bold 12, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define CrackUnnamed1705GraffitiShift             1705	//(Left Origin = 110, Top Origin = 75)
#define CrackAddressLabel                         1701	//(Left Origin = 9, Top Origin = 20, Usable = 1, Font = Standard)
#define CrackUnnamed1716Label                     1716	//(Left Origin = 9, Top Origin = 52, Usable = 1, Font = Standard)

//	Resource: tFRM 1900
#define ConnectForm                               1900	//(Left Origin = 20, Top Origin = 30, Width = 120, Height = 99, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define ConnectConnectButton                      1903	//(Left Origin = 13, Top Origin = 77, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ConnectCancelButton                       1904	//(Left Origin = 61, Top Origin = 77, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ConnectAddressField                       1902	//(Left Origin = 52, Top Origin = 18, Width = 60, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define ConnectOutputField                        1905	//(Left Origin = 10, Top Origin = 55, Width = 100, Height = 12, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 29, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define ConnectPasswordField                      1907	//(Left Origin = 52, Top Origin = 34, Width = 60, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define ConnectUnnamed1908GraffitiShift           1908	//(Left Origin = 108, Top Origin = 82)
#define ConnectAddressLabel                       1901	//(Left Origin = 9, Top Origin = 20, Usable = 1, Font = Standard)
#define ConnectPasswordLabel                      1906	//(Left Origin = 4, Top Origin = 34, Usable = 1, Font = Standard)

//	Resource: tFRM 2000
#define ServerForm                                2000	//(Left Origin = 1, Top Origin = 1, Width = 158, Height = 158, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define ServerLogoffButton                        2001	//(Left Origin = 24, Top Origin = 136, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ServerDatabaseButton                      2002	//(Left Origin = 24, Top Origin = 112, Width = 100, Height = 16, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold 12)
#define ServerAccountsPayableButton               2003	//(Left Origin = 24, Top Origin = 64, Width = 100, Height = 16, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold 12)
#define ServerAdministrationButton                2004	//(Left Origin = 24, Top Origin = 88, Width = 100, Height = 16, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold 12)
#define ServerMOTDField                           2005	//(Left Origin = 15, Top Origin = 18, Width = 130, Height = 36, Usable = 1, Editable = 0, Underline = 1, Single Line = 0, Dynamic Size = 1, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define ServerTimeoutField                        2007	//(Left Origin = 111, Top Origin = 135, Width = 30, Height = 12, Usable = 1, Editable = 0, Underline = 0, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define ServerTimeoutLabel                        2006	//(Left Origin = 71, Top Origin = 135, Usable = 1, Font = Standard)

//	Resource: tFRM 2100
#define ScanForm                                  2100	//(Left Origin = 1, Top Origin = 1, Width = 158, Height = 158, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define ScanScanButton                            2103	//(Left Origin = 16, Top Origin = 136, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ScanExitButton                            2104	//(Left Origin = 96, Top Origin = 136, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ScanStopButton                            2110	//(Left Origin = 56, Top Origin = 136, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ScanNetworkField                          2102	//(Left Origin = 71, Top Origin = 20, Width = 20, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 2, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define ScanFoundField                            2105	//(Left Origin = 71, Top Origin = 36, Width = 60, Height = 12, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 4, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define ScanTimeoutField                          2106	//(Left Origin = 71, Top Origin = 111, Width = 60, Height = 12, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 4, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define ScanUnnamed2111GraffitiShift              2111	//(Left Origin = 143, Top Origin = 143)
#define ScanNetworkLabel                          2101	//(Left Origin = 23, Top Origin = 20, Usable = 1, Font = Standard)
#define ScanScanningLabel                         2107	//(Left Origin = 23, Top Origin = 36, Usable = 1, Font = Standard)
#define ScanTimeoutLabel                          2108	//(Left Origin = 23, Top Origin = 111, Usable = 1, Font = Standard)
#define ScanFoundHostsList                        2109	//(Left Origin = 32, Top Origin = 56, Width = 100, Usable = 1, Font = Standard, Visible Items = 4)

//	Resource: tFRM 2200
#define ICEBreakerForm                            2200	//(Left Origin = 15, Top Origin = 20, Width = 120, Height = 80, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define ICEBreakerBreakButton                     2203	//(Left Origin = 10, Top Origin = 61, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ICEBreakerDoneButton                      2204	//(Left Origin = 58, Top Origin = 61, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ICEBreakerAddressField                    2202	//(Left Origin = 49, Top Origin = 20, Width = 60, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define ICEBreakerMessageField                    2205	//(Left Origin = 25, Top Origin = 36, Width = 70, Height = 12, Usable = 1, Editable = 0, Underline = 0, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define ICEBreakerUnnamed2206GraffitiShift        2206	//(Left Origin = 105, Top Origin = 68)
#define ICEBreakerAddressLabel                    2201	//(Left Origin = 9, Top Origin = 20, Usable = 1, Font = Standard)

//	Resource: tFRM 2300
#define NSLookupForm                              2300	//(Left Origin = 17, Top Origin = 30, Width = 130, Height = 80, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define NSLookupLookupButton                      2301	//(Left Origin = 5, Top Origin = 59, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define NSLookupOKButton                          2304	//(Left Origin = 46, Top Origin = 59, Width = 24, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define NSLookupSaveButton                        2307	//(Left Origin = 77, Top Origin = 59, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define NSLookupNameField                         2302	//(Left Origin = 42, Top Origin = 18, Width = 70, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define NSLookupAddressField                      2303	//(Left Origin = 42, Top Origin = 34, Width = 70, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define NSLookupUnnamed2308GraffitiShift          2308	//(Left Origin = 119, Top Origin = 66)
#define NSLookupNameLabel                         2305	//(Left Origin = 10, Top Origin = 18, Usable = 1, Font = Standard)
#define NSLookupAddressLabel                      2306	//(Left Origin = 2, Top Origin = 34, Usable = 1, Font = Standard)

//	Resource: tFRM 2400
#define AccountsPayableForm                       2400	//(Left Origin = 1, Top Origin = 1, Width = 158, Height = 158, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AccountsPayableTransferButton             2404	//(Left Origin = 40, Top Origin = 120, Width = 80, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AccountsPayableExitButton                 2405	//(Left Origin = 40, Top Origin = 136, Width = 80, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AccountsPayableBalanceField               2403	//(Left Origin = 50, Top Origin = 80, Width = 60, Height = 16, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Bold 12, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define AccountsPayableProgressGadget             2406	//(Left Origin = 30, Top Origin = 103, Width = 100, Height = 10, Usable = 1)
#define AccountsPayableWelcomeLabel               2401	//(Left Origin = 35, Top Origin = 18, Usable = 1, Font = Standard)
#define AccountsPayableBalanceLabel               2402	//(Left Origin = 35, Top Origin = 65, Usable = 1, Font = Bold 12)

//	Resource: tFRM 2600
#define AdministrationForm                        2600	//(Left Origin = 1, Top Origin = 1, Width = 158, Height = 158, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AdministrationExitButton                  2601	//(Left Origin = 62, Top Origin = 136, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AdministrationMOTDButton                  2602	//(Left Origin = 30, Top Origin = 40, Width = 100, Height = 16, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold 12)
#define AdministrationShutDownButton              2603	//(Left Origin = 30, Top Origin = 72, Width = 100, Height = 16, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold 12)

//	Resource: tFRM 2700
#define HostForm                                  2700	//(Left Origin = 1, Top Origin = 1, Width = 158, Height = 158, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define HostOkButton                              2711	//(Left Origin = 40, Top Origin = 128, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define HostDeleteButton                          2712	//(Left Origin = 88, Top Origin = 128, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define HostNameField                             2703	//(Left Origin = 63, Top Origin = 31, Width = 70, Height = 12, Usable = 1, Editable = 0, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define HostAddressField                          2704	//(Left Origin = 63, Top Origin = 47, Width = 70, Height = 12, Usable = 1, Editable = 0, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define HostPasswordField                         2706	//(Left Origin = 63, Top Origin = 63, Width = 70, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 8, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define HostHostnameLabel                         2701	//(Left Origin = 15, Top Origin = 31, Usable = 1, Font = Standard)
#define HostAddressLabel                          2702	//(Left Origin = 15, Top Origin = 47, Usable = 1, Font = Standard)
#define HostPasswordLabel                         2705	//(Left Origin = 15, Top Origin = 63, Usable = 1, Font = Standard)
#define HostWorkingPushButton                     2707	//(Left Origin = 32, Top Origin = 88, Width = 50, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define HostCrackedPushButton                     2708	//(Left Origin = 83, Top Origin = 88, Width = 50, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define HostShutDownPushButton                    2709	//(Left Origin = 32, Top Origin = 101, Width = 50, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define HostICEPushButton                         2710	//(Left Origin = 83, Top Origin = 101, Width = 50, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define HostGroupID                               1

//	Resource: tFRM 2800
#define MOTDForm                                  2800	//(Left Origin = 1, Top Origin = 1, Width = 158, Height = 110, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define MOTDDoneButton                            2803	//(Left Origin = 56, Top Origin = 80, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MOTDMOTDField                             2801	//(Left Origin = 15, Top Origin = 31, Width = 130, Height = 36, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 1, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MOTDUnnamed2804GraffitiShift              2804	//(Left Origin = 143, Top Origin = 95)
#define MOTDOldMOTDLabel                          2802	//(Left Origin = 7, Top Origin = 15, Usable = 1, Font = Standard)

//	Resource: tFRM 2900
#define DatabaseForm                              2900	//(Left Origin = 1, Top Origin = 1, Width = 158, Height = 158, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define DatabaseDoneButton                        2901	//(Left Origin = 60, Top Origin = 136, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define DatabaseSourceCodeButton                  2902	//(Left Origin = 16, Top Origin = 80, Width = 120, Height = 16, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold 12)
#define DatabasePayrollButton                     2903	//(Left Origin = 16, Top Origin = 80, Width = 120, Height = 16, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold 12)
#define DatabaseUFOButton                         2904	//(Left Origin = 16, Top Origin = 80, Width = 120, Height = 16, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold 12)
#define DatabaseUploadSourceButton                2908	//(Left Origin = 16, Top Origin = 80, Width = 120, Height = 16, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold 12)
#define DatabaseUploadPayrollButton               2909	//(Left Origin = 16, Top Origin = 80, Width = 120, Height = 16, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold 12)
#define DatabaseUploadUFOButton                   2910	//(Left Origin = 16, Top Origin = 80, Width = 120, Height = 16, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold 12)
#define DatabaseNoDataField                       2905	//(Left Origin = 60, Top Origin = 23, Width = 40, Height = 12, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define DatabaseDataField                         2906	//(Left Origin = 31, Top Origin = 39, Width = 100, Height = 36, Usable = 1, Editable = 0, Underline = 0, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define DatabaseProgressGadget                    2907	//(Left Origin = 30, Top Origin = 111, Width = 100, Height = 10, Usable = 1)

//	Resource: tFRM 3000
#define RegisterForm                              3000	//(Left Origin = 1, Top Origin = 1, Width = 158, Height = 158, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define RegisterRegisterButton                    3003	//(Left Origin = 24, Top Origin = 136, Width = 48, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define RegisterDoneButton                        3006	//(Left Origin = 80, Top Origin = 136, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define RegisterKeyField                          3005	//(Left Origin = 47, Top Origin = 111, Width = 70, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define RegisterPUNLabel                          3001	//(Left Origin = 7, Top Origin = 39, Usable = 1, Font = Standard)
#define RegisterRegCodeLabel                      3002	//(Left Origin = 7, Top Origin = 65, Usable = 1, Font = Standard)
#define RegisterKeyLabel                          3004	//(Left Origin = 31, Top Origin = 95, Usable = 1, Font = Standard)

//	Resource: tFRM 2500
#define GameOverForm                              2500	//(Left Origin = 50, Top Origin = 60, Width = 60, Height = 30, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define GameOverGameOverLabel                     2501	//(Left Origin = 3, Top Origin = 7, Usable = 1, Font = Bold 12)

//	Resource: tFRM 3100
#define CheatForm                                 3100	//(Left Origin = 1, Top Origin = 79, Width = 158, Height = 80, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define CheatDoneButton                           3101	//(Left Origin = 40, Top Origin = 58, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define CheatCheatButton                          3104	//(Left Origin = 88, Top Origin = 58, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define CheatCheatField                           3102	//(Left Origin = 39, Top Origin = 33, Width = 80, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 35, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define CheatGSIGraffitiShift                     3105	//(Left Origin = 143, Top Origin = 65)
#define CheatCheatLabel                           3103	//(Left Origin = 39, Top Origin = 17, Usable = 1, Font = Standard)

//	Resource: tFRM 3200
#define ShutdownForm                              3200	//(Left Origin = 1, Top Origin = 1, Width = 158, Height = 158, Usable = 1, Modal = 1, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1000
#define NotEnoughCreditsAlert                     1000
#define NotEnoughCreditsOK                        0

//	Resource: Talt 1100
#define SWIncompatibleAlert                       1100
#define SWIncompatibleOK                          0

//	Resource: Talt 1200
#define ResetGameAlert                            1200
#define ResetGameYes                              0
#define ResetGameNo                               1

//	Resource: Talt 1300
#define DeleteHostAlert                           1300
#define DeleteHostYes                             0
#define DeleteHostNo                              1

//	Resource: Talt 1400
#define RegisterAlert                             1400
#define RegisterOK                                0

//	Resource: Talt 1500
#define DeleteEmailAlert                          1500
#define DeleteEmailYes                            0
#define DeleteEmailNo                             1

//	Resource: Talt 1600
#define NoSourceAlert                             1600
#define NoSourceOK                                0

//	Resource: Talt 1700
#define NoPayrollAlert                            1700
#define NoPayrollOK                               0

//	Resource: Talt 1800
#define NoUFOAlert                                1800
#define NoUFOOK                                   0

//	Resource: Talt 1900
#define RegCheatAlert                             1900
#define RegCheatOK                                0


//	Resource: MBAR 1000
#define AlphaHackerMainMenuBar                    1000


//	Resource: MENU 1000
#define OptionsMenu                               1000
#define OptionsAboutAlphaHacker                   1000
#define OptionsRegister                           1002
#define OptionsCheat                              1003

//	Resource: MENU 1100
#define GameMenu                                  1100
#define GameUserInfo                              1100
#define GameSWInventory                           1101
#define GameResetGame                             1103


//	Resource: tSTR 1000
#define untitledString                            1000	// ""

//	Resource: tSTR 1100
#define EmailUFOMessageString                     1100	// "You've succeeded in exposing a government UFO coverup by hacking into government systems!  You must warn the public and upload this data to govtwatch.com!"

//	Resource: tSTR 1200
#define EmailWelcomeMessageString                 1200	// "We hope you enjoy your network access.  Please feel free to use the network as you wish, although hacking will not be tolerated. Our password is alpharez.  Thanks, Joe at Alpha.net -- an alpharez company"

//	Resource: tSTR 1300
#define EmailGeekMessageString                    1300	// "We need to shut down this server!  Please Hurry!  Their password is panaman."

//	Resource: tSTR 1400
#define EmailMusicMessageString                   1400	// "music.com is flooding the net with spam! We don't know their password! See if you can crack it."

//	Resource: tSTR 1500
#define EmailCrackMessageString                   1500	// "Incident alert!  Script kiddies at crack.com are running DDOS attacks on our servers.  We've gotten reports that they are also attacking servers at sfw.com.  Our security experts are working on the problem.  -- Bill"

//	Resource: tSTR 1600
#define EmailPornMessageString                    1600	// "We've found an illegal porn site on our network! "We're working now to disable it.  It's called porno.net.  Please don't access it.  -- Thanks."

//	Resource: tSTR 1700
#define EmailWinnukeMessageString                 1700	// "The source of the denial of service attacks are at winnuke.org.  We're working on disconnecting them from the net, but we're having a little trouble.  Everything should be resolved soon.   -- Thanks."

//	Resource: tSTR 1800
#define EmailWelcomeFromString                    1800	// "joe@alpha.net"

//	Resource: tSTR 1900
#define EmailWelcomeSubjectString                 1900	// "Welcome to Alpha.Net!"

//	Resource: tSTR 2000
#define EmailGeekFromString                       2000	// "csh@haxor.com"

//	Resource: tSTR 2100
#define EmailGeekSubjectString                    2100	// "geekempire.com sucks"

//	Resource: tSTR 2200
#define EmailMusicFromString                      2200	// "csh@haxor.com"

//	Resource: tSTR 2300
#define EmailMusicSubjectString                   2300	// "take down music.com!"

//	Resource: tSTR 2400
#define EmailCrackFromString                      2400	// "b@winblows.net"

//	Resource: tSTR 2500
#define EmailCrackSubjectString                   2500	// "beware crack.com"

//	Resource: tSTR 2600
#define EmailPornFromString                       2600	// "joe@alpha.net"

//	Resource: tSTR 2700
#define EmailPornSubjectString                    2700	// "Porn site detected!"

//	Resource: tSTR 2800
#define EmailWinnukeFromString                    2800	// "joe@alpha.net"

//	Resource: tSTR 2900
#define EmailWinnukeSubjectString                 2900	// "Win Nuke"

//	Resource: tSTR 3000
#define EmailUFOFromString                        3000	// "anonymous"

//	Resource: tSTR 3100
#define EmailUFOSubjectString                     3100	// "UFOs!"

//	Resource: tSTR 3200
#define HostNameCerealString                      3200	// "cereal.com"

//	Resource: tSTR 3300
#define HostMOTDCerealString                      3300	// "Cereal.com has all the healthy cereals"

//	Resource: tSTR 3400
#define HostNameGoatboyString                     3400	// "goatboy.com"

//	Resource: tSTR 3500
#define HostMOTDGoatboyString                     3500	// "Baaaaaaa!"

//	Resource: tSTR 3600
#define HostNameReligionString                    3600	// "religion.org"

//	Resource: tSTR 3700
#define HostMOTDReligionString                    3700	// "Praise Jesus!"

//	Resource: tSTR 3800
#define HostNameCnewsString                       3800	// "cnews.com"

//	Resource: tSTR 3900
#define HostMOTDCnewsString                       3900	// "All the news that's fit to print!"

//	Resource: tSTR 4000
#define HostNameArmyString                        4000	// "army.mil"

//	Resource: tSTR 4100
#define HostMOTDArmyString                        4100	// "Be all that you can be!"

//	Resource: tSTR 4200
#define HostNameWinblowsString                    4200	// "winblows.net"

//	Resource: tSTR 4300
#define HostMOTDWinblowsString                    4300	// "We make crappy OS's!"

//	Resource: tSTR 4400
#define HostNameHaxorString                       4400	// "haxor.com"

//	Resource: tSTR 4500
#define HostMOTDHaxorString                       4500	// "31337 h@x0r1n6!"

//	Resource: tSTR 4600
#define HostNameArchitectString                   4600	// "architect.com"

//	Resource: tSTR 4700
#define HostMOTDArchitectString                   4700	// "We build stuff up good!"

//	Resource: tSTR 4800
#define HostNameCyclingString                     4800	// "cycling.com"

//	Resource: tSTR 4900
#define HostMOTDCyclingString                     4900	// "Visit ohiocycling.com!"

//	Resource: tSTR 5000
#define HostNameEgyptString                       5000	// "egypt.com"

//	Resource: tSTR 5100
#define HostMOTDEgyptString                       5100	// "Welcome to the Egyptian tourism server."

//	Resource: tSTR 5200
#define HostNameMusicString                       5200	// "music.com"

//	Resource: tSTR 5300
#define HostMOTDMusicString                       5300	// "Please buy lots of CDs from us!"

//	Resource: tSTR 5400
#define HostNameSfwString                         5400	// "sfw.com"

//	Resource: tSTR 5500
#define HostMOTDSfwString                         5500	// "For all your software needs"

//	Resource: tSTR 5600
#define HostNameAlquedaString                     5600	// "alqueda.org"

//	Resource: tSTR 5700
#define HostMOTDAlquedaString                     5700	// "Help us destroy the infidel Americans!"

//	Resource: tSTR 5800
#define HostNameBlackhatString                    5800	// "blackhat.com"

//	Resource: tSTR 5900
#define HostMOTDBlackhatString                    5900	// "Building solid unix-based software"

//	Resource: tSTR 6000
#define HostNameCrackString                       6000	// "crack.com"

//	Resource: tSTR 6100
#define HostMOTDCrackString                       6100	// "That's why they call it dope."

//	Resource: tSTR 6200
#define HostNamePornoString                       6200	// "porno.net"

//	Resource: tSTR 6300
#define HostMOTDPornoString                       6300	// "We specialize in illegal porn!"

//	Resource: tSTR 6400
#define HostName2600String                        6400	// "2600.com"

//	Resource: tSTR 6500
#define HostMOTD2600String                        6500	// "Hacking into the 21st century!"

//	Resource: tSTR 6600
#define HostNameOctogonString                     6600	// "octogon.gov"

//	Resource: tSTR 6700
#define HostMOTDOctogonString                     6700	// "Classified Access Only!"

//	Resource: tSTR 6800
#define HostNameCongoString                       6800	// "congo.com"

//	Resource: tSTR 6900
#define HostMOTDCongoString                       6900	// "We sell everything."

//	Resource: tSTR 7000
#define HostNameUbayString                        7000	// "ubay.com"

//	Resource: tSTR 7100
#define HostMOTDUbayString                        7100	// "Most Popular Auction Site!"

//	Resource: tSTR 7200
#define HostNameSlashnerdString                   7200	// "slashnerd.org"

//	Resource: tSTR 7300
#define HostMOTDSlashnerdString                   7300	// "Nerd News for Nerds.  Stuff that matters."

//	Resource: tSTR 7400
#define HostNameAtstickString                     7400	// "atstick.com"

//	Resource: tSTR 7500
#define HostMOTDAtstickString                     7500	// "Security is our Business."

//	Resource: tSTR 7600
#define HostNamePalmsoftString                    7600	// "palmsoft.com"

//	Resource: tSTR 7700
#define HostMOTDPalmsoftString                    7700	// "We make Palm Pilot Software"

//	Resource: tSTR 7800
#define HostNameWinnukeString                     7800	// "winnuke.org"

//	Resource: tSTR 7900
#define HostMOTDWinnukeString                     7900	// "Distributors of Annoying Denial of Service Software!"

//	Resource: tSTR 8000
#define HostNameYokelString                       8000	// "yokel.com"

//	Resource: tSTR 8100
#define HostMOTDYokelString                       8100	// "Alphanet's Finest Search Engine!"

//	Resource: tSTR 8200
#define HostNameAlphabankString                   8200	// "alphabank.com"

//	Resource: tSTR 8300
#define HostMOTDAlphabankString                   8300	// "Let us nickel and dime you!"

//	Resource: tSTR 8400
#define HostNamePayyouString                      8400	// "payyou.com"

//	Resource: tSTR 8500
#define HostMOTDPayyouString                      8500	// "Send money over the net using Email!"

//	Resource: tSTR 8600
#define HostNameUsmintString                      8600	// "usmint.gov"

//	Resource: tSTR 8700
#define HostMOTDUsmintString                      8700	// "We're running low on gold bars!"

//	Resource: tSTR 8800
#define HostNamePearString                        8800	// "pear.com"

//	Resource: tSTR 8900
#define HostMOTDPearString                        8900	// "A pear a day keeps the doctor away."

//	Resource: tSTR 9000
#define HostNameWeatherString                     9000	// "weather.com"

//	Resource: tSTR 9100
#define HostMOTDWeatherString                     9100	// "The forecast for today is cloudy with a chance of showers"

//	Resource: tSTR 9200
#define HostNameBooksString                       9200	// "books.com"

//	Resource: tSTR 9300
#define HostMOTDBooksString                       9300	// "Your online library and book store!"

//	Resource: tSTR 9400
#define HostNameNovaString                        9400	// "nova.com"

//	Resource: tSTR 9500
#define HostMOTDNovaString                        9500	// "The planet's #1 space site."

//	Resource: tSTR 9600
#define HostNameTradersString                     9600	// "traders.com"

//	Resource: tSTR 9700
#define HostMOTDTradersString                     9700	// "Traders is an addictive online role-playing game."

//	Resource: tSTR 9800
#define HostNameHifiString                        9800	// "hifi.com"

//	Resource: tSTR 9900
#define HostMOTDHifiString                        9900	// "Dedicated to awesome sound."

//	Resource: tSTR 10000
#define HostNameNapsterString                     10000	// "napster.com"

//	Resource: tSTR 10100
#define HostMOTDNapsterString                     10100	// "long live  P2P file sharing!"

//	Resource: tSTR 10200
#define HostNameSummitString                      10200	// "summit.org"

//	Resource: tSTR 10300
#define HostMOTDSummitString                      10300	// "Save the whales!"

//	Resource: tSTR 10400
#define HostNameEbankString                       10400	// "ebank.com"

//	Resource: tSTR 10500
#define HostMOTDEbankString                       10500	// "Get a free umbrella with your new checking account!"

//	Resource: tSTR 10600
#define HostNameEpetsString                       10600	// "epets.com"

//	Resource: tSTR 10700
#define HostMOTDEpetsString                       10700	// "Buy your pet food online!  Good idea, huh?"

//	Resource: tSTR 10800
#define HostNameMicroshaftString                  10800	// "microshaft.com"

//	Resource: tSTR 10900
#define HostMOTDMicroshaftString                  10900	// "Resistance is Futile!"

//	Resource: tSTR 11000
#define HostNameAohellString                      11000	// "aohell.com"

//	Resource: tSTR 11100
#define HostMOTDAohellString                      11100	// "Do not attempt to adjust your set. We control the horizontal and the vertical."

//	Resource: tSTR 11200
#define HostNameNewgroundsString                  11200	// "newgrounds.com"

//	Resource: tSTR 11300
#define HostMOTDNewgroundsString                  11300	// "The problems of the future today!"

//	Resource: tSTR 11400
#define HostNameMobiusfactString                  11400	// "mobiusfact.com"

//	Resource: tSTR 11500
#define HostMOTDMobiusfactString                  11500	// "Working hard to bring you the worst!"

//	Resource: tSTR 11600
#define HostNameHexagonString                     11600	// "hexagon.mil"

//	Resource: tSTR 11700
#define HostMOTDHexagonString                     11700	// "Government conspiracies found here!"

//	Resource: tSTR 11800
#define EmailWinblowsMessageString                11800	// "winblows.net is distributing an OS that is spying on users systems.  Please help us shut down this server to stop their distribution!"

//	Resource: tSTR 11900
#define EmailWinblowsFromString                   11900	// "j@haxor.com"

//	Resource: tSTR 12000
#define EmailWinblowsSubjectString                12000	// "stop winblows!"

//	Resource: tSTR 12100
#define EmailClueMessageString                    12100	// "octogon.gov has address:"

//	Resource: tSTR 12200
#define EmailClueFromString                       12200	// "anonymous"

//	Resource: tSTR 12300
#define EmailClueSubjectString                    12300	// "Gov't secrets"

//	Resource: tSTR 12400
#define HostClueOctogonString                     12400	// "Government secrets are on Hexagon.mil:"

//	Resource: tSTR 12500
#define HostNameGovtWatchString                   12500	// "govtwatch.com"

//	Resource: tSTR 12600
#define HostMOTDGovtWatchString                   12600	// "We keep tabs on the government so you don't have to!"

//	Resource: tSTR 12700
#define EmailUpUFOMessageString                   12700	// "Thanks for uploading the Government UFO Data.  We have found it to be news worthy and we're running this on our web site and in print.  Good work!"

//	Resource: tSTR 12800
#define EmailUpUFOFromString                      12800	// "j@gwatch.com"

//	Resource: tSTR 12900
#define EmailUpUFOSubjectString                   12900	// "Thanks!"

//	Resource: tSTR 13000
#define HostNameSourceFString                     13000	// "sourcef.net"

//	Resource: tSTR 13100
#define HostMOTDSourceFString                     13100	// "Welcome to SourceF.  We make source code open to the public."

//	Resource: tSTR 13200
#define EmailSourceMessageString                  13200	// "We hear you're one of the best new hackers on the net.  Please upload any source code to sourcef.net  and we'll give you a nice reward."

//	Resource: tSTR 13300
#define EmailSourceFromString                     13300	// "w@sourcef.net"

//	Resource: tSTR 13400
#define EmailSourceSubjectString                  13400	// "Need Source!"

//	Resource: tSTR 13500
#define EmailPayrollMessageString                 13500	// "Upload your payroll data to newgrounds.com for a reward.  Just don't ask what we'll do with it."

//	Resource: tSTR 13600
#define EmailPayrollFromString                    13600	// "anonymous"

//	Resource: tSTR 13700
#define EmailPayrollSubjectString                 13700	// "Payroll data"

//	Resource: tSTR 13800
#define CheatQuantaString                         13800	// "oracle"

//	Resource: tSTR 13900
#define CheatGovtICEString                        13900	// "delphi"

//	Resource: tSTR 14000
#define CheatMoneyString                          14000	// "whammy"

//	Resource: tSTR 14100
#define CheatSuperSniffString                     14100	// "ardvaark"


//	Resource: PICT 1001
#define Bitmap                                    1001

//	Resource: PICT 1002
#define Bitmap2                                   1002

//	Resource: PICT 1008
#define Bitmap3                                   1008

//	Resource: PICT 1011
#define Bitmap4                                   1011

//	Resource: PICT 1012
#define Bitmap5                                   1012

//	Resource: PICT 1018
#define Bitmap6                                   1018

//	Resource: PICT 1101
#define EmailIconBitmap                           1101

//	Resource: PICT 1201
#define CrackedIconBitmap                         1201

//	Resource: PICT 1301
#define NothingIconBitmap                         1301

//	Resource: PICT 1401
#define BitmapID1401Bitmap                        1401

//	Resource: PICT 1501
#define ScanIconBitmap                            1501

//	Resource: PICT 1601
#define ICEIconBitmap                             1601

//	Resource: PICT 1701
#define BitmapID1701Bitmap                        1701

//	Resource: PICT 1801
#define BitmapID1801Bitmap                        1801

//	Resource: PICT 1901
#define BitmapID1901Bitmap                        1901

//	Resource: PICT 2001
#define BitmapID2001Bitmap                        2001

//	Resource: PICT 2101
#define BitmapID2101Bitmap                        2101

//	Resource: PICT 2201
#define BitmapID2201Bitmap                        2201

//	Resource: PICT 2301
#define BitmapID2301Bitmap                        2301

//	Resource: PICT 2401
#define BitmapID2401Bitmap                        2401

//	Resource: PICT 2008
#define BitmapID2008Bitmap                        2008

//	Resource: PICT 1908
#define BitmapID1908Bitmap                        1908

//	Resource: PICT 1808
#define BitmapID1808Bitmap                        1808

//	Resource: PICT 1708
#define BitmapID1708Bitmap                        1708

//	Resource: PICT 1608
#define BitmapID1608Bitmap                        1608

//	Resource: PICT 1508
#define BitmapID1508Bitmap                        1508

//	Resource: PICT 1408
#define BitmapID1408Bitmap                        1408

//	Resource: PICT 1208
#define BitmapID1208Bitmap                        1208

//	Resource: PICT 2108
#define BitmapID2108Bitmap                        2108

//	Resource: PICT 2208
#define BitmapID2208Bitmap                        2208

//	Resource: PICT 2308
#define BitmapID2308Bitmap                        2308

//	Resource: PICT 1308
#define BitmapID1308Bitmap                        1308


//	Resource: tbmf 1100
#define EmailBitmapFamily                         1100

//	Resource: tbmf 1200
#define CrackBitmapFamily                         1200

//	Resource: tbmf 1300
#define HostStatusNothingBitmapFamily             1300

//	Resource: tbmf 1400
#define ConnectBitmapFamily                       1400

//	Resource: tbmf 1500
#define ScanBitmapFamily                          1500

//	Resource: tbmf 1600
#define ICEBitmapFamily                           1600

//	Resource: tbmf 1700
#define TitleBitmapFamily                         1700

//	Resource: tbmf 1800
#define NSLookupBitmapFamily                      1800

//	Resource: tbmf 1900
#define CompStoreBitmapFamily                     1900

//	Resource: tbmf 2000
#define BlackHatBitmapFamily                      2000

//	Resource: tbmf 2100
#define HostStatusShutDownBitmapFamily            2100

//	Resource: tbmf 2200
#define HostStatusICEBitmapFamily                 2200

//	Resource: tbmf 2300
#define HostStatusCrackedBitmapFamily             2300

//	Resource: tbmf 2400
#define ConnectSelectedBitmapFamily               2400


//	Resource: taif 1000
#define Largeicons12and8bitsAppIconFamily         1000

//	Resource: taif 1001
#define Smallicons12and8bitsAppIconFamily         1001

