//	Header generated by Constructor for Palm OS¨ 1.6
//
//	Generated at 8:46:23 AM on Thursday, January 23, 2003
//
//	Generated for file: C:\Documents and Settings\clemens\My Documents\My Projects\AlphaHacker\Rsc\AlphaHacker.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"AlphaHacker"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainCreditsField                          1002	//(Left Origin = 104, Top Origin = 0, Width = 50, Height = 12, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainDollarLabel                           1001	//(Left Origin = 96, Top Origin = 0, Usable = 1, Font = Bold)
#define MainWelcomeLabel                          1005	//(Left Origin = 8, Top Origin = 24, Usable = 1, Font = Bold 12)
#define MainNSLookupTable                         1003	//(Left Origin = 0, Top Origin = 100, Width = 160, Height = 50, Editable = 1, Rows = 4)
#define MainEmailGraphicButton                    1004	//(Left Origin = 5, Top Origin = 150, Width = 12, Height = 10, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Bitmap Resource ID = 1100, Selected Bitmap Resource ID = 0)

//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOKButton                             1105	//(Left Origin = 58, Top Origin = 133, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutCopyrightLabel                       1101	//(Left Origin = 6, Top Origin = 40, Usable = 1, Font = Bold)
#define AboutTitleLabel                           1102	//(Left Origin = 6, Top Origin = 14, Usable = 1, Font = Bold 12)
#define AboutURLLabel                             1103	//(Left Origin = 6, Top Origin = 54, Usable = 1, Font = Bold)
#define AboutText2Label                           1104	//(Left Origin = 6, Top Origin = 30, Usable = 1, Font = Bold)

//	Resource: tFRM 1200
#define UserForm                                  1200	//(Left Origin = 1, Top Origin = 1, Width = 158, Height = 158, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define UserUnnamed1207Button                     1207	//(Left Origin = 16, Top Origin = 128, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define UserHandleField                           1202	//(Left Origin = 55, Top Origin = 15, Width = 85, Height = 16, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Bold 12, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define UserCPUField                              1204	//(Left Origin = 55, Top Origin = 31, Width = 85, Height = 16, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Bold 12, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define UserUnnamed1206Field                      1206	//(Left Origin = 55, Top Origin = 47, Width = 85, Height = 16, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Bold 12, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define UserUnnamed1209Field                      1209	//(Left Origin = 55, Top Origin = 63, Width = 85, Height = 16, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Bold 12, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define UserUnnamed1211Field                      1211	//(Left Origin = 55, Top Origin = 79, Width = 85, Height = 16, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Bold 12, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define UserUnnamed1213Field                      1213	//(Left Origin = 55, Top Origin = 95, Width = 85, Height = 16, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Bold 12, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define UserHandleLabel                           1201	//(Left Origin = 7, Top Origin = 15, Usable = 1, Font = Bold 12)
#define UserCPULabel                              1203	//(Left Origin = 7, Top Origin = 31, Usable = 1, Font = Bold 12)
#define UserRAMLabel                              1205	//(Left Origin = 7, Top Origin = 47, Usable = 1, Font = Bold 12)
#define UserMoneyLabel                            1208	//(Left Origin = 7, Top Origin = 63, Usable = 1, Font = Bold 12)
#define UserUnnamed1210Label                      1210	//(Left Origin = 7, Top Origin = 79, Usable = 1, Font = Bold 12)
#define UserRankLabel                             1212	//(Left Origin = 7, Top Origin = 95, Usable = 1, Font = Bold 12)

//	Resource: tFRM 1300
#define WelcomeForm                               1300	//(Left Origin = 1, Top Origin = 1, Width = 158, Height = 158, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define WelcomeLogonButton                        1306	//(Left Origin = 56, Top Origin = 112, Width = 40, Height = 18, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold 12)
#define WelcomeUnnamed1303Field                   1303	//(Left Origin = 63, Top Origin = 63, Width = 65, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define WelcomeUnnamed1305Field                   1305	//(Left Origin = 63, Top Origin = 79, Width = 65, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define WelcomeWelcomeLabel                       1301	//(Left Origin = 23, Top Origin = 31, Usable = 1, Font = Bold 12)
#define WelcomeUsernameLabel                      1302	//(Left Origin = 7, Top Origin = 63, Usable = 1, Font = Bold 12)
#define WelcomePasswordLabel                      1304	//(Left Origin = 7, Top Origin = 79, Usable = 1, Font = Bold 12)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0


//	Resource: MBAR 1000
#define ZeroCoolMainMenuBar                       1000


//	Resource: MENU 1000
#define OptionsMenu                               1000
#define OptionsAboutAlphaHacker                   1000

//	Resource: MENU 10000
#define EditMenu                                  10000
#define EditUndo                                  10000	//  Command Key: U
#define EditCut                                   10001	//  Command Key: X
#define EditCopy                                  10002	//  Command Key: C
#define EditPaste                                 10003	//  Command Key: P
#define EditSelectAll                             10004	//  Command Key: S
#define EditKeyboard                              10006	//  Command Key: K
#define EditGraffitiHelp                          10007	//  Command Key: G


//	Resource: PICT 1001
#define Bitmap                                    1001

//	Resource: PICT 1002
#define Bitmap2                                   1002

//	Resource: PICT 1008
#define Bitmap3                                   1008

//	Resource: PICT 1011
#define Bitmap4                                   1011

//	Resource: PICT 1012
#define Bitmap5                                   1012

//	Resource: PICT 1018
#define Bitmap6                                   1018

//	Resource: PICT 1101
#define BitmapID1101Bitmap                        1101


//	Resource: tbmf 1100
#define EmailBitmapFamily                         1100


//	Resource: taif 1000
#define Largeicons12and8bitsAppIconFamily         1000

//	Resource: taif 1001
#define Smallicons12and8bitsAppIconFamily         1001

