#include <PalmOS.h>

#include "AlphaHacker.h"
#include "AlphaHackerRsc.h"

Char g_passwords[NUMPASSWORDS][9];

static void AHDBInitPasswords() {
	StrCopy(g_passwords[0], "creole");
	StrCopy(g_passwords[1], "goatboy");
	StrCopy(g_passwords[2], "jessaves");
	StrCopy(g_passwords[3], "network");
	StrCopy(g_passwords[4], "squadron");
	StrCopy(g_passwords[5], "villain");
	StrCopy(g_passwords[6], "solaris");
	StrCopy(g_passwords[7], "database");
	StrCopy(g_passwords[8], "violator");
	StrCopy(g_passwords[9], "building");
	StrCopy(g_passwords[10], "pyramid");
	StrCopy(g_passwords[11], "mozart");
	StrCopy(g_passwords[12], "cougar");
	StrCopy(g_passwords[13], "software");
	StrCopy(g_passwords[14], "isolate");
	StrCopy(g_passwords[15], "blackdog");
	StrCopy(g_passwords[16], "reddog");
	StrCopy(g_passwords[17], "beagle");
	StrCopy(g_passwords[18], "weiner");
	StrCopy(g_passwords[19], "koolaid");
	StrCopy(g_passwords[20], "matlock");
	StrCopy(g_passwords[21], "socrates");
	StrCopy(g_passwords[22], "gandalf");
	StrCopy(g_passwords[23], "patriot");
	StrCopy(g_passwords[24], "unixgod");
	StrCopy(g_passwords[25], "thunder");
	StrCopy(g_passwords[26], "navigate");
	StrCopy(g_passwords[27], "hydrogen");
	StrCopy(g_passwords[28], "therapy");
	StrCopy(g_passwords[29], "nitrogen");
	StrCopy(g_passwords[30], "biology");
	StrCopy(g_passwords[31], "rhythm");
	StrCopy(g_passwords[32], "poetry");
	StrCopy(g_passwords[33], "firefox");
	StrCopy(g_passwords[34], "frogface");
	StrCopy(g_passwords[35], "breadbox");
	StrCopy(g_passwords[36], "cruiser");
	StrCopy(g_passwords[37], "security");
	StrCopy(g_passwords[38], "positron");
	StrCopy(g_passwords[39], "negative");
	StrCopy(g_passwords[40], "toyota");
	StrCopy(g_passwords[41], "thanatos");
	StrCopy(g_passwords[42], "objectiv");
	StrCopy(g_passwords[43], "sphynx");
	StrCopy(g_passwords[44], "sneakers");
	StrCopy(g_passwords[45], "managers");
	StrCopy(g_passwords[46], "homemade");
	StrCopy(g_passwords[47], "smuckers");
	StrCopy(g_passwords[48], "theaters");
	StrCopy(g_passwords[49], "qwestsux");
}

static void AHDBShufflePasswords() {
	UInt16 i, j;
	Char *temp;
	temp = MemPtrNew(9);
	
	for(i=0; i<NUMPASSWORDS; i++) {
		// j = (SysRandom(0)/((1+sysRandomMax)/(NUMPASSWORDS-1)));
		j = SysRandom(0)%(NUMPASSWORDS-1);
		if(j > NUMPASSWORDS) j = NUMPASSWORDS;
		StrCopy(temp, g_passwords[j]);
		StrCopy(g_passwords[j], g_passwords[i]);
		StrCopy(g_passwords[i], temp);
	}
	MemPtrFree(temp);
}

void AHDBInitHostRecords() {
	MemHandle nameH, MOTDH, clueH;
	Char *name, *MOTD, *clue;
	
	AHDBInitPasswords();
	AHDBShufflePasswords();

	g_hosts[0].level = 1;
	StrCopy(g_hosts[0].name, "alpha.net");
	StrCopy(g_hosts[0].passcode, "alpharez");
	g_hosts[0].timeout = 84;
	StrCopy(g_hosts[0].motd, "Welcome to Alpha.net! Please don't hack us!");
	g_hosts[0].balance = 550;
	g_hosts[0].hasICE = false;
	g_hosts[0].hasGovtICE = false;
	g_hosts[0].hasAdmin = true;
	g_hosts[0].MOTDChanged = false;
	g_hosts[0].FundsTaken = false;
	g_hosts[0].hasSourceCode = false;
	g_hosts[0].hasPayrollData = false;
	g_hosts[0].hasUFOData = false;
	g_hosts[0].wantsSourceCode = false;
	g_hosts[0].wantsPayrollData = false;
	g_hosts[0].wantsUFOData = false;

	nameH = DmGet1Resource(strRsc, HostNameCerealString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDCerealString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[1].level = 1;
	StrCopy(g_hosts[1].name, name);
	StrCopy(g_hosts[1].passcode, g_passwords[0]);
	g_hosts[1].timeout = 64;
	StrCopy(g_hosts[1].motd, MOTD);
	g_hosts[1].balance = 1000;
	g_hosts[1].hasICE = false;
	g_hosts[1].hasGovtICE = false;
	g_hosts[1].hasAdmin = true;
	g_hosts[1].MOTDChanged = false;
	g_hosts[1].FundsTaken = false;
	g_hosts[1].hasSourceCode = false;
	g_hosts[1].hasPayrollData = false;
	g_hosts[1].hasUFOData = false;
	g_hosts[1].wantsSourceCode = false;
	g_hosts[1].wantsPayrollData = false;
	g_hosts[1].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);
	
	nameH = DmGet1Resource(strRsc, HostNameGoatboyString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDGoatboyString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[2].level = 1;
	StrCopy(g_hosts[2].name, name);
	StrCopy(g_hosts[2].passcode, g_passwords[1]);
	g_hosts[2].timeout = 74;
	StrCopy(g_hosts[2].motd, MOTD);
	g_hosts[2].balance = 1000;
	g_hosts[2].hasICE = false;
	g_hosts[2].hasGovtICE = false;
	g_hosts[2].hasAdmin = true;
	g_hosts[2].MOTDChanged = false;
	g_hosts[2].FundsTaken = false;
	g_hosts[2].hasSourceCode = false;
	g_hosts[2].hasPayrollData = false;
	g_hosts[2].hasUFOData = false;
	g_hosts[2].wantsSourceCode = false;
	g_hosts[2].wantsPayrollData = false;
	g_hosts[2].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

	nameH = DmGet1Resource(strRsc, HostNameReligionString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDReligionString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[3].level = 1;
	StrCopy(g_hosts[3].name, name);
	StrCopy(g_hosts[3].passcode, g_passwords[2]);
	g_hosts[3].timeout = 65;
	StrCopy(g_hosts[3].motd, MOTD);
	g_hosts[3].balance = 10000;
	g_hosts[3].hasICE = true;
	g_hosts[3].hasGovtICE = false;
	g_hosts[3].hasAdmin = true;
	g_hosts[3].MOTDChanged = false;
	g_hosts[3].FundsTaken = false;
	g_hosts[3].hasSourceCode = false;
	g_hosts[3].hasPayrollData = false;
	g_hosts[3].hasUFOData = false;
	g_hosts[3].wantsSourceCode = false;
	g_hosts[3].wantsPayrollData = false;
	g_hosts[3].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

	nameH = DmGet1Resource(strRsc, HostNameCnewsString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDCnewsString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[4].level = 2;
	StrCopy(g_hosts[4].name, name);
	StrCopy(g_hosts[4].passcode, g_passwords[3]);
	g_hosts[4].timeout = 55;
	StrCopy(g_hosts[4].motd, MOTD);
	g_hosts[4].balance = 2500;
	g_hosts[4].hasICE = false;
	g_hosts[4].hasGovtICE = false;
	g_hosts[4].hasAdmin = true;
	g_hosts[4].MOTDChanged = false;
	g_hosts[4].FundsTaken = false;
	g_hosts[4].hasSourceCode = false;
	g_hosts[4].hasPayrollData = true;
	g_hosts[4].hasUFOData = false;
	g_hosts[4].wantsSourceCode = false;
	g_hosts[4].wantsPayrollData = false;
	g_hosts[4].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

	nameH = DmGet1Resource(strRsc, HostNameArmyString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDArmyString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[5].level = 3;
	StrCopy(g_hosts[5].name, name);
	StrCopy(g_hosts[5].passcode, g_passwords[4]);
	g_hosts[5].timeout = 55;
	StrCopy(g_hosts[5].motd, MOTD);
	g_hosts[5].balance = 200;
	g_hosts[5].hasICE = false;
	g_hosts[5].hasGovtICE = false;
	g_hosts[5].hasAdmin = true;
	g_hosts[5].MOTDChanged = false;
	g_hosts[5].FundsTaken = false;
	g_hosts[5].hasSourceCode = false;
	g_hosts[5].hasPayrollData = false;
	g_hosts[5].hasUFOData = false;
	g_hosts[5].wantsSourceCode = false;
	g_hosts[5].wantsPayrollData = false;
	g_hosts[5].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

	nameH = DmGet1Resource(strRsc, HostNameWinblowsString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDWinblowsString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[6].level = 3;
	StrCopy(g_hosts[6].name, name);
	StrCopy(g_hosts[6].passcode, g_passwords[5]);
	g_hosts[6].timeout = 51;
	StrCopy(g_hosts[6].motd, MOTD);
	g_hosts[6].balance = 5000;
	g_hosts[6].hasICE = true;
	g_hosts[6].hasGovtICE = false;
	g_hosts[6].hasAdmin = true;
	g_hosts[6].MOTDChanged = false;
	g_hosts[6].FundsTaken = false;
	g_hosts[6].hasSourceCode = true;
	g_hosts[6].hasPayrollData = false;
	g_hosts[6].hasUFOData = false;
	g_hosts[6].wantsSourceCode = false;
	g_hosts[6].wantsPayrollData = false;
	g_hosts[6].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);
	
	nameH = DmGet1Resource(strRsc, HostNameHaxorString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDHaxorString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[7].level = 1;
	StrCopy(g_hosts[7].name, name);
	StrCopy(g_hosts[7].passcode, g_passwords[6]);
	g_hosts[7].timeout = 85;
	StrCopy(g_hosts[7].motd, MOTD);
	g_hosts[7].balance = 300;
	g_hosts[7].hasICE = false;
	g_hosts[7].hasGovtICE = false;
	g_hosts[7].hasAdmin = true;
	g_hosts[7].MOTDChanged = false;
	g_hosts[7].FundsTaken = false;
	g_hosts[7].hasSourceCode = false;
	g_hosts[7].hasPayrollData = false;
	g_hosts[7].hasUFOData = false;
	g_hosts[7].wantsSourceCode = false;
	g_hosts[7].wantsPayrollData = false;
	g_hosts[7].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

	nameH = DmGet1Resource(strRsc, HostNameArchitectString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDArchitectString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[8].level = 2;
	StrCopy(g_hosts[8].name, name);
	StrCopy(g_hosts[8].passcode, g_passwords[7]);
	g_hosts[8].timeout = 54;
	StrCopy(g_hosts[8].motd, MOTD);
	g_hosts[8].balance = 2500;
	g_hosts[8].hasICE = false;
	g_hosts[8].hasGovtICE = false;
	g_hosts[8].hasAdmin = true;
	g_hosts[8].MOTDChanged = false;
	g_hosts[8].FundsTaken = false;
	g_hosts[8].hasSourceCode = false;
	g_hosts[8].hasPayrollData = true;
	g_hosts[8].hasUFOData = false;
	g_hosts[8].wantsSourceCode = false;
	g_hosts[8].wantsPayrollData = false;
	g_hosts[8].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

	g_hosts[9].level = 2;
	StrCopy(g_hosts[9].name, "geekempire.com");
	StrCopy(g_hosts[9].passcode, "panaman");
	g_hosts[9].timeout = 70;
	StrCopy(g_hosts[9].motd, "Play it like your mama showed you!");
	g_hosts[9].balance = 550;
	g_hosts[9].hasICE = false;
	g_hosts[9].hasGovtICE = false;
	g_hosts[9].hasAdmin = true;
	g_hosts[9].MOTDChanged = false;
	g_hosts[9].FundsTaken = false;
	g_hosts[9].hasSourceCode = false;
	g_hosts[9].hasPayrollData = false;
	g_hosts[9].hasUFOData = false;
	g_hosts[9].wantsSourceCode = false;
	g_hosts[9].wantsPayrollData = false;
	g_hosts[9].wantsUFOData = false;

	nameH = DmGet1Resource(strRsc, HostNameCyclingString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDCyclingString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[10].level = 2;
	StrCopy(g_hosts[10].name, name);
	StrCopy(g_hosts[10].passcode, g_passwords[8]);
	g_hosts[10].timeout = 55;
	StrCopy(g_hosts[10].motd, MOTD);
	g_hosts[10].balance = 200;
	g_hosts[10].hasICE = false;
	g_hosts[10].hasGovtICE = false;
	g_hosts[10].hasAdmin = true;
	g_hosts[10].MOTDChanged = false;
	g_hosts[10].FundsTaken = false;
	g_hosts[10].hasSourceCode = false;
	g_hosts[10].hasPayrollData = false;
	g_hosts[10].hasUFOData = false;
	g_hosts[10].wantsSourceCode = false;
	g_hosts[10].wantsPayrollData = false;
	g_hosts[10].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

	nameH = DmGet1Resource(strRsc, HostNameEgyptString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDEgyptString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[11].level = 2;
	StrCopy(g_hosts[11].name, name);
	StrCopy(g_hosts[11].passcode, g_passwords[9]);
	g_hosts[11].timeout = 40;
	StrCopy(g_hosts[11].motd, MOTD);
	g_hosts[11].balance = 2500;
	g_hosts[11].hasICE = false;
	g_hosts[11].hasGovtICE = false;
	g_hosts[11].hasAdmin = true;
	g_hosts[11].MOTDChanged = false;
	g_hosts[11].FundsTaken = false;
	g_hosts[11].hasSourceCode = false;
	g_hosts[11].hasPayrollData = false;
	g_hosts[11].hasUFOData = false;
	g_hosts[11].wantsSourceCode = false;
	g_hosts[11].wantsPayrollData = false;
	g_hosts[11].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

	nameH = DmGet1Resource(strRsc, HostNameMusicString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDMusicString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[12].level = 2;
	StrCopy(g_hosts[12].name, name);
	StrCopy(g_hosts[12].passcode, g_passwords[10]);
	g_hosts[12].timeout = 95;
	StrCopy(g_hosts[12].motd, MOTD);
	g_hosts[12].balance = 1200;
	g_hosts[12].hasICE = false;
	g_hosts[12].hasGovtICE = false;
	g_hosts[12].hasAdmin = true;
	g_hosts[12].MOTDChanged = false;
	g_hosts[12].FundsTaken = false;
	g_hosts[12].hasSourceCode = true;
	g_hosts[12].hasPayrollData = false;
	g_hosts[12].hasUFOData = false;
	g_hosts[12].wantsSourceCode = false;
	g_hosts[12].wantsPayrollData = false;
	g_hosts[12].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

	nameH = DmGet1Resource(strRsc, HostNameSfwString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDSfwString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[13].level = 2;
	StrCopy(g_hosts[13].name, name);
	StrCopy(g_hosts[13].passcode, g_passwords[11]);
	g_hosts[13].timeout = 79;
	StrCopy(g_hosts[13].motd, MOTD);
	g_hosts[13].balance = 200;
	g_hosts[13].hasICE = false;
	g_hosts[13].hasGovtICE = false;
	g_hosts[13].hasAdmin = true;
	g_hosts[13].MOTDChanged = false;
	g_hosts[13].FundsTaken = false;
	g_hosts[13].hasSourceCode = false;
	g_hosts[13].hasPayrollData = true;
	g_hosts[13].hasUFOData = false;
	g_hosts[13].wantsSourceCode = false;
	g_hosts[13].wantsPayrollData = false;
	g_hosts[13].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);
	
	nameH = DmGet1Resource(strRsc, HostNameAlquedaString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDAlquedaString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[14].level = 3;
	StrCopy(g_hosts[14].name, name);
	StrCopy(g_hosts[14].passcode, g_passwords[12]);
	g_hosts[14].timeout = 50;
	StrCopy(g_hosts[14].motd, MOTD);
	g_hosts[14].balance = 3500;
	g_hosts[14].hasICE = false;
	g_hosts[14].hasGovtICE = false;
	g_hosts[14].hasAdmin = true;
	g_hosts[14].MOTDChanged = false;
	g_hosts[14].FundsTaken = false;
	g_hosts[14].hasSourceCode = false;
	g_hosts[14].hasPayrollData = false;
	g_hosts[14].hasUFOData = false;
	g_hosts[14].wantsSourceCode = false;
	g_hosts[14].wantsPayrollData = false;
	g_hosts[14].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

	nameH = DmGet1Resource(strRsc, HostNameBlackhatString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDBlackhatString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[15].level = 3;
	StrCopy(g_hosts[15].name, name);
	StrCopy(g_hosts[15].passcode, g_passwords[13]);
	g_hosts[15].timeout = 50;
	StrCopy(g_hosts[15].motd, MOTD);
	g_hosts[15].balance = 2500;
	g_hosts[15].hasICE = false;
	g_hosts[15].hasGovtICE = false;
	g_hosts[15].hasAdmin = true;
	g_hosts[15].MOTDChanged = false;
	g_hosts[15].FundsTaken = false;
	g_hosts[15].hasSourceCode = true;
	g_hosts[15].hasPayrollData = false;
	g_hosts[15].hasUFOData = false;
	g_hosts[15].wantsSourceCode = false;
	g_hosts[15].wantsPayrollData = false;
	g_hosts[15].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);
	
	nameH = DmGet1Resource(strRsc, HostNameCrackString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDCrackString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[16].level = 3;
	StrCopy(g_hosts[16].name, name);
	StrCopy(g_hosts[16].passcode, g_passwords[14]);
	g_hosts[16].timeout = 95;
	StrCopy(g_hosts[16].motd, MOTD);
	g_hosts[16].balance = 500;
	g_hosts[16].hasICE = false;
	g_hosts[16].hasGovtICE = false;
	g_hosts[16].hasAdmin = true;
	g_hosts[16].MOTDChanged = false;
	g_hosts[16].FundsTaken = false;
	g_hosts[16].hasSourceCode = false;
	g_hosts[16].hasPayrollData = false;
	g_hosts[16].hasUFOData = false;
	g_hosts[16].wantsSourceCode = false;
	g_hosts[16].wantsPayrollData = false;
	g_hosts[16].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

	nameH = DmGet1Resource(strRsc, HostNamePornoString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDPornoString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[17].level = 3;
	StrCopy(g_hosts[17].name, name);
	StrCopy(g_hosts[17].passcode, g_passwords[15]);
	g_hosts[17].timeout = 65;
	StrCopy(g_hosts[17].motd, MOTD);
	g_hosts[17].balance = 1500;
	g_hosts[17].hasICE = false;
	g_hosts[17].hasGovtICE = false;
	g_hosts[17].hasAdmin = true;
	g_hosts[17].MOTDChanged = false;
	g_hosts[17].FundsTaken = false;
	g_hosts[17].hasSourceCode = false;
	g_hosts[17].hasPayrollData = false;
	g_hosts[17].hasUFOData = false;
	g_hosts[17].wantsSourceCode = false;
	g_hosts[17].wantsPayrollData = false;
	g_hosts[17].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

	nameH = DmGet1Resource(strRsc, HostName2600String);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTD2600String);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[18].level = 3;
	StrCopy(g_hosts[18].name, name);
	StrCopy(g_hosts[18].passcode, g_passwords[16]);
	g_hosts[18].timeout = 65;
	StrCopy(g_hosts[18].motd, MOTD);
	g_hosts[18].balance = 600;
	g_hosts[18].hasICE = false;
	g_hosts[18].hasGovtICE = false;
	g_hosts[18].hasAdmin = true;
	g_hosts[18].MOTDChanged = false;
	g_hosts[18].FundsTaken = false;
	g_hosts[18].hasSourceCode = true;
	g_hosts[18].hasPayrollData = false;
	g_hosts[18].hasUFOData = false;
	g_hosts[18].wantsSourceCode = false;
	g_hosts[18].wantsPayrollData = false;
	g_hosts[18].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

	nameH = DmGet1Resource(strRsc, HostNameOctogonString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDOctogonString);
	MOTD = MemHandleLock(MOTDH);
	clueH = DmGet1Resource(strRsc, HostClueOctogonString);
	clue = MemHandleLock(clueH);
	g_hosts[19].level = 3;
	StrCopy(g_hosts[19].name, name);
	StrCopy(g_hosts[19].passcode, g_passwords[17]);
	g_hosts[19].timeout = 25;
	StrCopy(g_hosts[19].motd, MOTD);
	StrCopy(g_hosts[19].clue, clue);
	g_hosts[19].balance = 40000;
	g_hosts[19].hasICE = false;
	g_hosts[19].hasGovtICE = true;
	g_hosts[19].hasAdmin = true;
	g_hosts[19].MOTDChanged = false;
	g_hosts[19].FundsTaken = false;
	g_hosts[19].hasSourceCode = true;
	g_hosts[19].hasPayrollData = false;
	g_hosts[19].hasUFOData = false;
	g_hosts[19].hasClue = true;
	g_hosts[19].wantsSourceCode = false;
	g_hosts[19].wantsPayrollData = false;
	g_hosts[19].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

	nameH = DmGet1Resource(strRsc, HostNameCongoString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDCongoString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[20].level = 3;
	StrCopy(g_hosts[20].name, name);
	StrCopy(g_hosts[20].passcode, g_passwords[18]);
	g_hosts[20].timeout = 55;
	StrCopy(g_hosts[20].motd, MOTD);
	g_hosts[20].balance = 2000;
	g_hosts[20].hasICE = false;
	g_hosts[20].hasGovtICE = false;
	g_hosts[20].hasAdmin = true;
	g_hosts[20].MOTDChanged = false;
	g_hosts[20].FundsTaken = false;
	g_hosts[20].hasSourceCode = false;
	g_hosts[20].hasPayrollData = true;
	g_hosts[20].hasUFOData = true;
	g_hosts[20].wantsSourceCode = false;
	g_hosts[20].wantsPayrollData = false;
	g_hosts[20].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

	nameH = DmGet1Resource(strRsc, HostNameUbayString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDUbayString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[21].level = 3;
	StrCopy(g_hosts[21].name, name);
	StrCopy(g_hosts[21].passcode, g_passwords[19]);
	g_hosts[21].timeout = 55;
	StrCopy(g_hosts[21].motd, MOTD);
	g_hosts[21].balance = 2000;
	g_hosts[21].hasICE = false;
	g_hosts[21].hasGovtICE = false;
	g_hosts[21].hasAdmin = true;
	g_hosts[21].MOTDChanged = false;
	g_hosts[21].FundsTaken = false;
	g_hosts[21].hasSourceCode = false;
	g_hosts[21].hasPayrollData = false;
	g_hosts[21].hasUFOData = false;
	g_hosts[21].wantsSourceCode = false;
	g_hosts[21].wantsPayrollData = false;
	g_hosts[21].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

	nameH = DmGet1Resource(strRsc, HostNameSlashnerdString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDSlashnerdString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[22].level = 3;
	StrCopy(g_hosts[22].name, name);
	StrCopy(g_hosts[22].passcode, g_passwords[20]);
	g_hosts[22].timeout = 65;
	StrCopy(g_hosts[22].motd, MOTD);
	g_hosts[22].balance = 1000;
	g_hosts[22].hasICE = false;
	g_hosts[22].hasGovtICE = false;
	g_hosts[22].hasAdmin = true;
	g_hosts[22].MOTDChanged = false;
	g_hosts[22].FundsTaken = false;
	g_hosts[22].hasSourceCode = false;
	g_hosts[22].hasPayrollData = false;
	g_hosts[22].hasUFOData = false;
	g_hosts[22].wantsSourceCode = false;
	g_hosts[22].wantsPayrollData = false;
	g_hosts[22].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

	nameH = DmGet1Resource(strRsc, HostNameAtstickString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDAtstickString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[23].level = 3;
	StrCopy(g_hosts[23].name, name);
	StrCopy(g_hosts[23].passcode, g_passwords[21]);
	g_hosts[23].timeout = 55;
	StrCopy(g_hosts[23].motd, MOTD);
	g_hosts[23].balance = 1500;
	g_hosts[23].hasICE = false;
	g_hosts[23].hasGovtICE = false;
	g_hosts[23].hasAdmin = true;
	g_hosts[23].MOTDChanged = false;
	g_hosts[23].FundsTaken = false;
	g_hosts[23].hasSourceCode = true;
	g_hosts[23].hasPayrollData = false;
	g_hosts[23].hasUFOData = false;
	g_hosts[23].wantsSourceCode = false;
	g_hosts[23].wantsPayrollData = false;
	g_hosts[23].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

	nameH = DmGet1Resource(strRsc, HostNamePalmsoftString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDPalmsoftString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[24].level = 3;
	StrCopy(g_hosts[24].name, name);
	StrCopy(g_hosts[24].passcode, g_passwords[22]);
	g_hosts[24].timeout = 65;
	StrCopy(g_hosts[24].motd, MOTD);
	g_hosts[24].balance = 3500;
	g_hosts[24].hasICE = false;
	g_hosts[24].hasGovtICE = false;
	g_hosts[24].hasAdmin = true;
	g_hosts[24].MOTDChanged = false;
	g_hosts[24].FundsTaken = false;
	g_hosts[24].hasSourceCode = true;
	g_hosts[24].hasPayrollData = false;
	g_hosts[24].hasUFOData = false;
	g_hosts[24].wantsSourceCode = false;
	g_hosts[24].wantsPayrollData = false;
	g_hosts[24].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

	nameH = DmGet1Resource(strRsc, HostNameWinnukeString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDWinnukeString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[25].level = 3;
	StrCopy(g_hosts[25].name, name);
	StrCopy(g_hosts[25].passcode, g_passwords[23]);
	g_hosts[25].timeout = 63;
	StrCopy(g_hosts[25].motd, MOTD);
	g_hosts[25].balance = 500;
	g_hosts[25].hasICE = false;
	g_hosts[25].hasGovtICE = false;
	g_hosts[25].hasAdmin = true;
	g_hosts[25].MOTDChanged = false;
	g_hosts[25].FundsTaken = false;
	g_hosts[25].hasSourceCode = false;
	g_hosts[25].hasPayrollData = false;
	g_hosts[25].hasUFOData = false;
	g_hosts[25].wantsSourceCode = false;
	g_hosts[25].wantsPayrollData = false;
	g_hosts[25].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

	nameH = DmGet1Resource(strRsc, HostNameYokelString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDYokelString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[26].level = 3;
	StrCopy(g_hosts[26].name, name);
	StrCopy(g_hosts[26].passcode, g_passwords[24]);
	g_hosts[26].timeout = 50;
	StrCopy(g_hosts[26].motd, MOTD);
	g_hosts[26].balance = 2100;
	g_hosts[26].hasICE = false;
	g_hosts[26].hasGovtICE = false;
	g_hosts[26].hasAdmin = true;
	g_hosts[26].MOTDChanged = false;
	g_hosts[26].FundsTaken = false;
	g_hosts[26].hasSourceCode = false;
	g_hosts[26].hasPayrollData = false;
	g_hosts[26].hasUFOData = false;
	g_hosts[26].wantsSourceCode = false;
	g_hosts[26].wantsPayrollData = false;
	g_hosts[26].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

	nameH = DmGet1Resource(strRsc, HostNameAlphabankString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDAlphabankString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[27].level = 3;
	StrCopy(g_hosts[27].name, name);
	StrCopy(g_hosts[27].passcode, g_passwords[25]);
	g_hosts[27].timeout = 30;
	StrCopy(g_hosts[27].motd, MOTD);
	g_hosts[27].balance = 50000;
	g_hosts[27].hasICE = true;
	g_hosts[27].hasGovtICE = false;
	g_hosts[27].hasAdmin = true;
	g_hosts[27].MOTDChanged = false;
	g_hosts[27].FundsTaken = false;
	g_hosts[27].hasSourceCode = false;
	g_hosts[27].hasPayrollData = true;
	g_hosts[27].hasUFOData = false;
	g_hosts[27].wantsSourceCode = false;
	g_hosts[27].wantsPayrollData = false;
	g_hosts[27].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

	nameH = DmGet1Resource(strRsc, HostNamePayyouString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDPayyouString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[28].level = 3;
	StrCopy(g_hosts[28].name, name);
	StrCopy(g_hosts[28].passcode, g_passwords[26]);
	g_hosts[28].timeout = 30;
	StrCopy(g_hosts[28].motd, MOTD);
	g_hosts[28].balance = 50000;
	g_hosts[28].hasICE = false;
	g_hosts[28].hasGovtICE = false;
	g_hosts[28].hasAdmin = true;
	g_hosts[28].MOTDChanged = false;
	g_hosts[28].FundsTaken = false;
	g_hosts[28].hasSourceCode = false;
	g_hosts[28].hasPayrollData = true;
	g_hosts[28].hasUFOData = false;
	g_hosts[28].wantsSourceCode = false;
	g_hosts[28].wantsPayrollData = false;
	g_hosts[28].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);
	
	nameH = DmGet1Resource(strRsc, HostNameUsmintString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDUsmintString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[29].level = 3;
	StrCopy(g_hosts[29].name, name);
	StrCopy(g_hosts[29].passcode, g_passwords[27]);
	g_hosts[29].timeout = 35;
	StrCopy(g_hosts[29].motd, MOTD);
	g_hosts[29].balance = 75000;
	g_hosts[29].hasICE = true;
	g_hosts[29].hasGovtICE = false;
	g_hosts[29].hasAdmin = true;
	g_hosts[29].MOTDChanged = false;
	g_hosts[29].FundsTaken = false;
	g_hosts[29].hasSourceCode = false;
	g_hosts[29].hasPayrollData = false;
	g_hosts[29].hasUFOData = false;
	g_hosts[29].wantsSourceCode = false;
	g_hosts[29].wantsPayrollData = false;
	g_hosts[29].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

	nameH = DmGet1Resource(strRsc, HostNamePearString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDPearString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[30].level = 3;
	StrCopy(g_hosts[30].name, name);
	StrCopy(g_hosts[30].passcode, g_passwords[28]);
	g_hosts[30].timeout = 55;
	StrCopy(g_hosts[30].motd, MOTD);
	g_hosts[30].balance = 500;
	g_hosts[30].hasICE = false;
	g_hosts[30].hasGovtICE = false;
	g_hosts[30].hasAdmin = true;
	g_hosts[30].MOTDChanged = false;
	g_hosts[30].FundsTaken = false;
	g_hosts[30].hasSourceCode = false;
	g_hosts[30].hasPayrollData = false;
	g_hosts[30].hasUFOData = false;
	g_hosts[30].wantsSourceCode = false;
	g_hosts[30].wantsPayrollData = false;
	g_hosts[30].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

	nameH = DmGet1Resource(strRsc, HostNameWeatherString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDWeatherString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[31].level = 3;
	StrCopy(g_hosts[31].name, name);
	StrCopy(g_hosts[31].passcode, g_passwords[29]);
	g_hosts[31].timeout = 35;
	StrCopy(g_hosts[31].motd, MOTD);
	g_hosts[31].balance = 5000;
	g_hosts[31].hasICE = false;
	g_hosts[31].hasGovtICE = false;
	g_hosts[31].hasAdmin = true;
	g_hosts[31].MOTDChanged = false;
	g_hosts[31].FundsTaken = false;
	g_hosts[31].hasSourceCode = false;
	g_hosts[31].hasPayrollData = true;
	g_hosts[31].hasUFOData = false;
	g_hosts[31].wantsSourceCode = false;
	g_hosts[31].wantsPayrollData = false;
	g_hosts[31].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

	nameH = DmGet1Resource(strRsc, HostNameBooksString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDBooksString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[32].level = 3;
	StrCopy(g_hosts[32].name, name);
	StrCopy(g_hosts[32].passcode, g_passwords[30]);
	g_hosts[32].timeout = 65;
	StrCopy(g_hosts[32].motd, MOTD);
	g_hosts[32].balance = 5000;
	g_hosts[32].hasICE = false;
	g_hosts[32].hasGovtICE = false;
	g_hosts[32].hasAdmin = true;
	g_hosts[32].MOTDChanged = false;
	g_hosts[32].FundsTaken = false;
	g_hosts[32].hasSourceCode = false;
	g_hosts[32].hasPayrollData = true;
	g_hosts[32].hasUFOData = false;
	g_hosts[32].wantsSourceCode = false;
	g_hosts[32].wantsPayrollData = false;
	g_hosts[32].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

	nameH = DmGet1Resource(strRsc, HostNameNovaString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDNovaString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[33].level = 3;
	StrCopy(g_hosts[33].name, name);
	StrCopy(g_hosts[33].passcode, g_passwords[31]);
	g_hosts[33].timeout = 65;
	StrCopy(g_hosts[33].motd, MOTD);
	g_hosts[33].balance = 6000;
	g_hosts[33].hasICE = false;
	g_hosts[33].hasGovtICE = false;
	g_hosts[33].hasAdmin = true;
	g_hosts[33].MOTDChanged = false;
	g_hosts[33].FundsTaken = false;
	g_hosts[33].hasSourceCode = false;
	g_hosts[33].hasPayrollData = false;
	g_hosts[33].hasUFOData = false;
	g_hosts[33].wantsSourceCode = false;
	g_hosts[33].wantsPayrollData = false;
	g_hosts[33].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

	nameH = DmGet1Resource(strRsc, HostNameTradersString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDTradersString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[34].level = 3;
	StrCopy(g_hosts[34].name, name);
	StrCopy(g_hosts[34].passcode, g_passwords[32]);
	g_hosts[34].timeout = 55;
	StrCopy(g_hosts[34].motd, MOTD);
	g_hosts[34].balance = 1000;
	g_hosts[34].hasICE = false;
	g_hosts[34].hasGovtICE = false;
	g_hosts[34].hasAdmin = true;
	g_hosts[34].MOTDChanged = false;
	g_hosts[34].FundsTaken = false;
	g_hosts[34].hasSourceCode = true;
	g_hosts[34].hasPayrollData = false;
	g_hosts[34].hasUFOData = false;
	g_hosts[34].wantsSourceCode = false;
	g_hosts[34].wantsPayrollData = false;
	g_hosts[34].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

	nameH = DmGet1Resource(strRsc, HostNameHifiString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDHifiString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[35].level = 3;
	StrCopy(g_hosts[35].name, name);
	StrCopy(g_hosts[35].passcode, g_passwords[33]);
	g_hosts[35].timeout = 55;
	StrCopy(g_hosts[35].motd, MOTD);
	g_hosts[35].balance = 1000;
	g_hosts[35].hasICE = false;
	g_hosts[35].hasGovtICE = false;
	g_hosts[35].hasAdmin = true;
	g_hosts[35].MOTDChanged = false;
	g_hosts[35].FundsTaken = false;
	g_hosts[35].hasSourceCode = false;
	g_hosts[35].hasPayrollData = false;
	g_hosts[35].hasUFOData = false;
	g_hosts[35].wantsSourceCode = false;
	g_hosts[35].wantsPayrollData = false;
	g_hosts[35].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

	nameH = DmGet1Resource(strRsc, HostNameNapsterString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDNapsterString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[36].level = 3;
	StrCopy(g_hosts[36].name, name);
	StrCopy(g_hosts[36].passcode, g_passwords[34]);
	g_hosts[36].timeout = 65;
	StrCopy(g_hosts[36].motd, MOTD);
	g_hosts[36].balance = 500;
	g_hosts[36].hasICE = false;
	g_hosts[36].hasGovtICE = false;
	g_hosts[36].hasAdmin = true;
	g_hosts[36].MOTDChanged = false;
	g_hosts[36].FundsTaken = false;
	g_hosts[36].hasSourceCode = false;
	g_hosts[36].hasPayrollData = false;
	g_hosts[36].hasUFOData = false;
	g_hosts[36].wantsSourceCode = false;
	g_hosts[36].wantsPayrollData = false;
	g_hosts[36].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

	nameH = DmGet1Resource(strRsc, HostNameSummitString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDSummitString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[37].level = 3;
	StrCopy(g_hosts[37].name, name);
	StrCopy(g_hosts[37].passcode, g_passwords[35]);
	g_hosts[37].timeout = 55;
	StrCopy(g_hosts[37].motd, MOTD);
	g_hosts[37].balance = 5500;
	g_hosts[37].hasICE = false;
	g_hosts[37].hasGovtICE = false;
	g_hosts[37].hasAdmin = true;
	g_hosts[37].MOTDChanged = false;
	g_hosts[37].FundsTaken = false;
	g_hosts[37].hasSourceCode = false;
	g_hosts[37].hasPayrollData = false;
	g_hosts[37].hasUFOData = false;
	g_hosts[37].wantsSourceCode = false;
	g_hosts[37].wantsPayrollData = false;
	g_hosts[37].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

	nameH = DmGet1Resource(strRsc, HostNameEbankString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDEbankString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[38].level = 3;
	StrCopy(g_hosts[38].name, name);
	StrCopy(g_hosts[38].passcode, g_passwords[36]);
	g_hosts[38].timeout = 55;
	StrCopy(g_hosts[38].motd, MOTD);
	g_hosts[38].balance = 62000;
	g_hosts[38].hasICE = true;
	g_hosts[38].hasGovtICE = false;
	g_hosts[38].hasAdmin = true;
	g_hosts[38].MOTDChanged = false;
	g_hosts[38].FundsTaken = false;
	g_hosts[38].hasSourceCode = false;
	g_hosts[38].hasPayrollData = false;
	g_hosts[38].hasUFOData = false;
	g_hosts[38].wantsSourceCode = false;
	g_hosts[38].wantsPayrollData = false;
	g_hosts[38].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

	nameH = DmGet1Resource(strRsc, HostNameEpetsString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDEpetsString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[39].level = 3;
	StrCopy(g_hosts[39].name, name);
	StrCopy(g_hosts[39].passcode, g_passwords[37]);
	g_hosts[39].timeout = 55;
	StrCopy(g_hosts[39].motd, MOTD);
	g_hosts[39].balance = 750;
	g_hosts[39].hasICE = false;
	g_hosts[39].hasGovtICE = false;
	g_hosts[39].hasAdmin = true;
	g_hosts[39].MOTDChanged = false;
	g_hosts[39].FundsTaken = false;
	g_hosts[39].hasSourceCode = false;
	g_hosts[39].hasPayrollData = false;
	g_hosts[39].hasUFOData = false;
	g_hosts[39].wantsSourceCode = false;
	g_hosts[39].wantsPayrollData = false;
	g_hosts[39].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

	nameH = DmGet1Resource(strRsc, HostNameMicroshaftString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDMicroshaftString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[40].level = 3;
	StrCopy(g_hosts[40].name, name);
	StrCopy(g_hosts[40].passcode, g_passwords[38]);
	g_hosts[40].timeout = 25;
	StrCopy(g_hosts[40].motd, MOTD);
	g_hosts[40].balance = 10000;
	g_hosts[40].hasICE = true;
	g_hosts[40].hasGovtICE = false;
	g_hosts[40].hasAdmin = true;
	g_hosts[40].MOTDChanged = false;
	g_hosts[40].FundsTaken = false;
	g_hosts[40].hasSourceCode = true;
	g_hosts[40].hasPayrollData = false;
	g_hosts[40].hasUFOData = false;
	g_hosts[40].wantsSourceCode = false;
	g_hosts[40].wantsPayrollData = false;
	g_hosts[40].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

	nameH = DmGet1Resource(strRsc, HostNameAohellString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDAohellString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[41].level = 3;
	StrCopy(g_hosts[41].name, name);
	StrCopy(g_hosts[41].passcode, g_passwords[39]);
	g_hosts[41].timeout = 25;
	StrCopy(g_hosts[41].motd, MOTD);
	g_hosts[41].balance = 10000;
	g_hosts[41].hasICE = true;
	g_hosts[41].hasGovtICE = false;
	g_hosts[41].hasAdmin = true;
	g_hosts[41].MOTDChanged = false;
	g_hosts[41].FundsTaken = false;
	g_hosts[41].hasSourceCode = false;
	g_hosts[41].hasPayrollData = true;
	g_hosts[41].hasUFOData = false;
	g_hosts[41].wantsSourceCode = false;
	g_hosts[41].wantsPayrollData = false;
	g_hosts[41].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

	nameH = DmGet1Resource(strRsc, HostNameNewgroundsString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDNewgroundsString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[42].level = 3;
	StrCopy(g_hosts[42].name, name);
	StrCopy(g_hosts[42].passcode, g_passwords[40]);
	g_hosts[42].timeout = 55;
	StrCopy(g_hosts[42].motd, MOTD);
	g_hosts[42].balance = 550;
	g_hosts[42].hasICE = false;
	g_hosts[42].hasGovtICE = false;
	g_hosts[42].hasAdmin = true;
	g_hosts[42].MOTDChanged = false;
	g_hosts[42].FundsTaken = false;
	g_hosts[42].hasSourceCode = false;
	g_hosts[42].hasPayrollData = false;
	g_hosts[42].hasUFOData = false;
	g_hosts[42].wantsSourceCode = false;
	g_hosts[42].wantsPayrollData = true;
	g_hosts[42].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

	nameH = DmGet1Resource(strRsc, HostNameMobiusfactString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDMobiusfactString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[43].level = 3;
	StrCopy(g_hosts[43].name, name);
	StrCopy(g_hosts[43].passcode, g_passwords[41]);
	g_hosts[43].timeout = 35;
	StrCopy(g_hosts[43].motd, MOTD);
	g_hosts[43].balance = 100;
	g_hosts[43].hasICE = false;
	g_hosts[43].hasGovtICE = false;
	g_hosts[43].hasAdmin = true;
	g_hosts[43].MOTDChanged = false;
	g_hosts[43].FundsTaken = false;
	g_hosts[43].hasSourceCode = false;
	g_hosts[43].hasPayrollData = false;
	g_hosts[43].hasUFOData = false;
	g_hosts[43].wantsSourceCode = false;
	g_hosts[43].wantsPayrollData = false;
	g_hosts[43].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

	nameH = DmGet1Resource(strRsc, HostNameHexagonString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDHexagonString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[44].level = 3;
	StrCopy(g_hosts[44].name, name);
	StrCopy(g_hosts[44].passcode, g_passwords[42]);
	g_hosts[44].timeout = 25;
	StrCopy(g_hosts[44].motd, MOTD);
	g_hosts[44].balance = 8000;
	g_hosts[44].hasICE = false;
	g_hosts[44].hasGovtICE = true;
	g_hosts[44].hasAdmin = true;
	g_hosts[44].MOTDChanged = false;
	g_hosts[44].FundsTaken = false;
	g_hosts[44].hasSourceCode = false;
	g_hosts[44].hasPayrollData = false;
	g_hosts[44].hasUFOData = true;
	g_hosts[44].wantsSourceCode = false;
	g_hosts[44].wantsPayrollData = false;
	g_hosts[44].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);
	
	nameH = DmGet1Resource(strRsc, HostNameGovtWatchString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDGovtWatchString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[45].level = 3;
	StrCopy(g_hosts[45].name, name);
	StrCopy(g_hosts[45].passcode, g_passwords[43]);
	g_hosts[45].timeout = 25;
	StrCopy(g_hosts[45].motd, MOTD);
	g_hosts[45].balance = 10000;
	g_hosts[45].hasICE = true;
	g_hosts[45].hasGovtICE = false;
	g_hosts[45].hasAdmin = true;
	g_hosts[45].MOTDChanged = false;
	g_hosts[45].FundsTaken = false;
	g_hosts[45].hasSourceCode = false;
	g_hosts[45].hasPayrollData = false;
	g_hosts[45].hasUFOData = false;
	g_hosts[45].wantsSourceCode = false;
	g_hosts[45].wantsPayrollData = false;
	g_hosts[45].wantsUFOData = true;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

	nameH = DmGet1Resource(strRsc, HostNameSourceFString);
	name = MemHandleLock(nameH);
	MOTDH = DmGet1Resource(strRsc, HostMOTDSourceFString);
	MOTD = MemHandleLock(MOTDH);
	g_hosts[46].level = 3;
	StrCopy(g_hosts[46].name, name);
	StrCopy(g_hosts[46].passcode, g_passwords[44]);
	g_hosts[46].timeout = 25;
	StrCopy(g_hosts[46].motd, MOTD);
	g_hosts[46].balance = 5000;
	g_hosts[46].hasICE = false;
	g_hosts[46].hasGovtICE = false;
	g_hosts[46].hasAdmin = true;
	g_hosts[46].MOTDChanged = false;
	g_hosts[46].FundsTaken = false;
	g_hosts[46].hasSourceCode = false;
	g_hosts[46].hasPayrollData = false;
	g_hosts[46].hasUFOData = false;
	g_hosts[46].wantsSourceCode = true;
	g_hosts[46].wantsPayrollData = false;
	g_hosts[46].wantsUFOData = false;
	DmReleaseResource(nameH);
	DmReleaseResource(MOTDH);

}

void AHDBInitEmailRecords() {
	MemHandle msgH, fromH, subjectH, recordH;
	Char *msg, *from, *subject;
	Char *temp, *msgclue;
	Int16 host;
	netDBRecord *recP;
	
	msgH = DmGet1Resource(strRsc, EmailWelcomeMessageString);
	msg = MemHandleLock(msgH);
	fromH = DmGet1Resource(strRsc, EmailWelcomeFromString);
	from = MemHandleLock(fromH);
	subjectH = DmGet1Resource(strRsc, EmailWelcomeSubjectString);
	subject = MemHandleLock(subjectH);
	StrCopy(g_emails[0].from, from);
	StrCopy(g_emails[0].subject, subject);
	StrCopy(g_emails[0].message, msg);
	DmReleaseResource(msgH);
	DmReleaseResource(fromH);
	DmReleaseResource(subjectH);

	msgH = DmGet1Resource(strRsc, EmailGeekMessageString);
	msg = MemHandleLock(msgH);
	fromH = DmGet1Resource(strRsc, EmailGeekFromString);
	from = MemHandleLock(fromH);
	subjectH = DmGet1Resource(strRsc, EmailGeekSubjectString);
	subject = MemHandleLock(subjectH);
	StrCopy(g_emails[1].from, from);
	StrCopy(g_emails[1].subject, subject);
	StrCopy(g_emails[1].message, msg);
	DmReleaseResource(msgH);
	DmReleaseResource(fromH);
	DmReleaseResource(subjectH);

	msgH = DmGet1Resource(strRsc, EmailMusicMessageString);
	msg = MemHandleLock(msgH);
	fromH = DmGet1Resource(strRsc, EmailMusicFromString);
	from = MemHandleLock(fromH);
	subjectH = DmGet1Resource(strRsc, EmailMusicSubjectString);
	subject = MemHandleLock(subjectH);
	StrCopy(g_emails[2].from, from);
	StrCopy(g_emails[2].subject, subject);
	StrCopy(g_emails[2].message, msg);
	DmReleaseResource(msgH);
	DmReleaseResource(fromH);
	DmReleaseResource(subjectH);
	
	msgH = DmGet1Resource(strRsc, EmailCrackMessageString);
	msg = MemHandleLock(msgH);
	fromH = DmGet1Resource(strRsc, EmailCrackFromString);
	from = MemHandleLock(fromH);
	subjectH = DmGet1Resource(strRsc, EmailCrackSubjectString);
	subject = MemHandleLock(subjectH);
	StrCopy(g_emails[3].from, from);
	StrCopy(g_emails[3].subject, subject);
	StrCopy(g_emails[3].message, msg);
	DmReleaseResource(msgH);
	DmReleaseResource(fromH);
	DmReleaseResource(subjectH);

	msgH = DmGet1Resource(strRsc, EmailPornMessageString);
	msg = MemHandleLock(msgH);
	fromH = DmGet1Resource(strRsc, EmailPornFromString);
	from = MemHandleLock(fromH);
	subjectH = DmGet1Resource(strRsc, EmailPornSubjectString);
	subject = MemHandleLock(subjectH);
	StrCopy(g_emails[4].from, from);
	StrCopy(g_emails[4].subject, subject);
	StrCopy(g_emails[4].message, msg);
	DmReleaseResource(msgH);
	DmReleaseResource(fromH);
	DmReleaseResource(subjectH);

	msgH = DmGet1Resource(strRsc, EmailWinnukeMessageString);
	msg = MemHandleLock(msgH);
	fromH = DmGet1Resource(strRsc, EmailWinnukeFromString);
	from = MemHandleLock(fromH);
	subjectH = DmGet1Resource(strRsc, EmailWinnukeSubjectString);
	subject = MemHandleLock(subjectH);
	StrCopy(g_emails[5].from, from);
	StrCopy(g_emails[5].subject, subject);
	StrCopy(g_emails[5].message, msg);
	DmReleaseResource(msgH);
	DmReleaseResource(fromH);
	DmReleaseResource(subjectH);

	msgH = DmGet1Resource(strRsc, EmailWinblowsMessageString);
	msg = MemHandleLock(msgH);
	fromH = DmGet1Resource(strRsc, EmailWinblowsFromString);
	from = MemHandleLock(fromH);
	subjectH = DmGet1Resource(strRsc, EmailWinblowsSubjectString);
	subject = MemHandleLock(subjectH);
	StrCopy(g_emails[6].from, from);
	StrCopy(g_emails[6].subject, subject);
	StrCopy(g_emails[6].message, msg);

	msgH = DmGet1Resource(strRsc, EmailSourceMessageString);
	msg = MemHandleLock(msgH);
	fromH = DmGet1Resource(strRsc, EmailSourceFromString);
	from = MemHandleLock(fromH);
	subjectH = DmGet1Resource(strRsc, EmailSourceSubjectString);
	subject = MemHandleLock(subjectH);
	StrCopy(g_emails[7].from, from);
	StrCopy(g_emails[7].subject, subject);
	StrCopy(g_emails[7].message, msg);

	msgH = DmGet1Resource(strRsc, EmailPayrollMessageString);
	msg = MemHandleLock(msgH);
	fromH = DmGet1Resource(strRsc, EmailPayrollFromString);
	from = MemHandleLock(fromH);
	subjectH = DmGet1Resource(strRsc, EmailPayrollSubjectString);
	subject = MemHandleLock(subjectH);
	StrCopy(g_emails[8].from, from);
	StrCopy(g_emails[8].subject, subject);
	StrCopy(g_emails[8].message, msg);

	msgH = DmGet1Resource(strRsc, EmailClueMessageString);
	msg = MemHandleLock(msgH);
	fromH = DmGet1Resource(strRsc, EmailClueFromString);
	from = MemHandleLock(fromH);
	subjectH = DmGet1Resource(strRsc, EmailClueSubjectString);
	subject = MemHandleLock(subjectH);
	StrCopy(g_emails[9].from, from);
	StrCopy(g_emails[9].subject, subject);
	// add address to msg
	temp = MemPtrNew(25);
	msgclue = MemPtrNew(55);
	StrCopy(temp, "octogon.gov");
	host = AHDBFindHostByName(temp);
	recordH = DmQueryRecord(gNetDB, host);
	if(recordH) {
		recP = MemHandleLock(recordH);
		StrCopy(msgclue, msg);
		StrCat(msgclue, " ");
		StrIToA(temp, recP->network);
		StrCat(msgclue, temp);
		StrCat(msgclue, ".");
		StrIToA(temp, recP->host);
		StrCat(msgclue, temp);
		MemHandleUnlock(recordH);
	}
	StrCopy(g_emails[9].message, msgclue);
	MemPtrFree(temp);
	MemPtrFree(msgclue);

	msgH = DmGet1Resource(strRsc, EmailUFOMessageString);
	msg = MemHandleLock(msgH);
	fromH = DmGet1Resource(strRsc, EmailUFOFromString);
	from = MemHandleLock(fromH);
	subjectH = DmGet1Resource(strRsc, EmailUFOSubjectString);
	subject = MemHandleLock(subjectH);
	StrCopy(g_emails[10].from, from);
	StrCopy(g_emails[10].subject, subject);
	StrCopy(g_emails[10].message, msg);
	DmReleaseResource(msgH);
	DmReleaseResource(fromH);
	DmReleaseResource(subjectH);
	
	msgH = DmGet1Resource(strRsc, EmailUpUFOMessageString);
	msg = MemHandleLock(msgH);
	fromH = DmGet1Resource(strRsc, EmailUpUFOFromString);
	from = MemHandleLock(fromH);
	subjectH = DmGet1Resource(strRsc, EmailUpUFOSubjectString);
	subject = MemHandleLock(subjectH);
	StrCopy(g_emails[11].from, from);
	StrCopy(g_emails[11].subject, subject);
	StrCopy(g_emails[11].message, msg);
	DmReleaseResource(msgH);
	DmReleaseResource(fromH);
	DmReleaseResource(subjectH);


}

static void AHDBInitHostAddrs() {
	UInt16 addr, i, j;
	Boolean good;

	for(i=0; i<NUMHOSTS; i++) {
		do {
			good = true;
			addr = ((SysRandom(0)/(1+sysRandomMax/600))+1);
			for(j=0; j<=i; j++) 
				if(g_hostaddr[j] == addr) good = false;
		} while(good == false);
		g_hostaddr[i] = addr;
	}
}

void AHDBInitNetworkDatabase() {
	netDBRecord newRecord;
	MemHandle newRecordH;
	netDBRecord *newRecordP;
	Int16 host;
	UInt16 index = 0;
	Err error;
	
	AHDBInitHostAddrs();
	for(host=0; host<NUMHOSTS; host++) {
		// create new record
		newRecord.network = (SysRandom(0)/(1+sysRandomMax/10))+1;
		newRecord.host = g_hostaddr[host];
		newRecord.level = g_hosts[host].level;
		StrCopy(newRecord.name, g_hosts[host].name);
		StrCopy(newRecord.passcode, g_hosts[host].passcode);
		newRecord.timeout = g_hosts[host].timeout;
		StrCopy(newRecord.motd, g_hosts[host].motd);
		newRecord.balance = g_hosts[host].balance;
		newRecord.hasICE = g_hosts[host].hasICE;
		newRecord.hasGovtICE = g_hosts[host].hasGovtICE;
		newRecord.hasAdmin = g_hosts[host].hasAdmin;
		newRecord.MOTDChanged = g_hosts[host].MOTDChanged;
		newRecord.FundsTaken = g_hosts[host].FundsTaken;
		newRecord.hasSourceCode = g_hosts[host].hasSourceCode;
		newRecord.hasPayrollData = g_hosts[host].hasPayrollData;
		newRecord.hasUFOData = g_hosts[host].hasUFOData;
		newRecord.wantsSourceCode = g_hosts[host].wantsSourceCode;
		newRecord.wantsPayrollData = g_hosts[host].wantsPayrollData;
		newRecord.wantsUFOData = g_hosts[host].wantsUFOData;
		newRecord.hasClue = g_hosts[host].hasClue;
		if(g_hosts[host].hasClue) 
			StrCopy(newRecord.clue, g_hosts[host].clue);
		/* newRecordH = DmNewRecord(gNetDB, &index, sizeof(netDBRecord));
		newRecordP = MemHandleLock(newRecordH);
		DmWrite(newRecordP, 0, &newRecord, sizeof(netDBRecord));
		MemHandleUnlock(newRecordH);
		DmReleaseRecord(gNetDB, index, true); */
		newRecordH = DmNewHandle(gNetDB, sizeof(newRecord));
		newRecordP = MemHandleLock(newRecordH);
		DmWrite(newRecordP, 0, &newRecord, sizeof(newRecord));
		MemHandleUnlock(newRecordH);
		error = DmAttachRecord(gNetDB, &index, newRecordH, NULL);
		if(error) MemHandleFree(newRecordH);
	}
}

void AHDBAddEmailToDatabase(UInt16 email) {
	emailDBRecord newRecord;
	MemHandle newRecordH;
	emailDBRecord *newRecordP;
	UInt16 index = 0;
	
	StrCopy(newRecord.from, g_emails[email].from);
	StrCopy(newRecord.subject, g_emails[email].subject);
	StrCopy(newRecord.message, g_emails[email].message);
	newRecordH = DmNewRecord(gEmailDB, &index, sizeof(newRecord));
	newRecordP = MemHandleLock(newRecordH);
	DmWrite(newRecordP, 0, &newRecord, sizeof(newRecord));
	MemHandleUnlock(newRecordH);
	DmReleaseRecord(gEmailDB, index, true);
}

void AHDBInitEmailDatabase() {
	emailDBRecord newRecord;
	MemHandle newRecordH;
	emailDBRecord *newRecordP;
	UInt16 index = 0;
	UInt16 email;
	
	//AHDBInitEmailRecords();
	for(email=0; email<NUMEMAILS; email++) {
		StrCopy(newRecord.from, g_emails[email].from);
		StrCopy(newRecord.subject, g_emails[email].subject);
		StrCopy(newRecord.message, g_emails[email].message);
		newRecordH = DmNewRecord(gEmailDB, &index, sizeof(newRecord));
		newRecordP = MemHandleLock(newRecordH);
		DmWrite(newRecordP, 0, &newRecord, sizeof(newRecord));
		MemHandleUnlock(newRecordH);
		DmReleaseRecord(gEmailDB, index, true);
	}
}

Int16 AHDBFindHostByName(Char *hostname) {
	Int16 record;
	MemHandle recH;
	netDBRecord *recP;
	Int16 comp;
	
	record = 0;
	do {
		recH = DmQueryRecord(gNetDB, record);
		if(recH) {
			recP = MemHandleLock(recH);
			comp = StrCompare(recP->name, hostname);
			if(comp == 0) {
				MemHandleUnlock(recH);
				return record;
			}
			MemHandleUnlock(recH);
			record++;
		}
	} while(recH != NULL);
	return NOSUCHRECORD;
}

Int16 AHDBFindHostByAddr(Char *address) {
	Int16 record;
	MemHandle recH;
	netDBRecord *recP;
	Int16 comp;
	Char *addr, *temp;
	
	record = 0;
	addr = MemPtrNew(20);
	temp = MemPtrNew(20);
	do {
		recH = DmQueryRecord(gNetDB, record);
		if(recH) {
			recP = MemHandleLock(recH);
			StrIToA(temp, recP->network);
			StrCopy(addr, temp);
			StrCat(addr, ".");
			StrIToA(temp, recP->host);
			StrCat(addr, temp);
			comp = StrCompare(addr, address);
			if(comp == 0) {
				MemHandleUnlock(recH);
				MemPtrFree(addr);
				MemPtrFree(temp);
				return record;
			}
			MemHandleUnlock(recH);
			record++;
		}
	} while(recH != NULL);
	MemPtrFree(addr);
	MemPtrFree(temp);
	return NOSUCHRECORD;
}

Err AHDBGetNetworkDatabase() {
	Err error=0;
	UInt16 mode = dmModeReadWrite;
	LocalID netdbID;
	
	AHDBInitHostRecords();
	netdbID = DmFindDatabase(0, netDBName);
	if(netdbID) gNetDB = DmOpenDatabase(0, netdbID, mode);
	if(!gNetDB) {
		error = DmCreateDatabase(0, netDBName, appFileCreator, netDBType, false);
		if(error) return error;
		netdbID = DmFindDatabase(0, netDBName);
		gNetDB = DmOpenDatabase(0, netdbID, mode);
		if(!gNetDB) return DmGetLastErr();
		AHDBInitNetworkDatabase();
	}
	return error;
}

Err AHDBGetEmailDatabase() {
	Err error=0;
	UInt16 mode = dmModeReadWrite;
	LocalID emaildbID;
	
	AHDBInitEmailRecords();
	emaildbID = DmFindDatabase(0, emailDBName);
	if(emaildbID) gEmailDB = DmOpenDatabase(0, emaildbID, mode);
	if(!gEmailDB) {
		error = DmCreateDatabase(0, emailDBName, appFileCreator, emailDBType, false);
		if(error) return error;
		emaildbID = DmFindDatabase(0, emailDBName);
		gEmailDB = DmOpenDatabase(0, emaildbID, mode);
		if(!gEmailDB) return DmGetLastErr();
		AHDBInitEmailDatabase();
	}
	return error;
}

Err AHDBGetNSLookupDatabase() {
	Err error=0;
	UInt16 mode = dmModeReadWrite;
	LocalID nslookupdbID;
	
	nslookupdbID = DmFindDatabase(0, nslookupDBName);
	if(nslookupdbID) 
		gNSLookupDB = DmOpenDatabase(0, nslookupdbID, mode);
	if(!gNSLookupDB) {
		error = DmCreateDatabase(0, nslookupDBName, appFileCreator, nslookupDBType, false);
		if(error) return error;
		nslookupdbID = DmFindDatabase(0, nslookupDBName);
		gNSLookupDB = DmOpenDatabase(0, nslookupdbID, mode);
		if(!gNSLookupDB) return DmGetLastErr();
	}
	return error;
}